### ISSUE TITLE
能不能呼吁大型的开源项目增加996协议

### ISSUE THREAD

**Issue by zb2947244682** [Y1ran/Lambda-Stream-Dataprocess-Platform#16]
让那些大型项目的持有人，管理者，也抵制那些996不给加班费，压榨劳动力的公司，这样可以造成实际损失。

**Comment by SkyAndGround** [comment]
> 让那些大型项目的持有人，管理者，也抵制那些996不给加班费，压榨劳动力的公司，这样可以造成实际损失。

Support

**Comment by recolic** [comment]
release a draft for the license first...

(my chinese input method booooomed on Manjaro Linux so I have to speak in english... sigh)

**Comment by GeemChen** [comment]
强烈支持

**Comment by Alan110** [comment]
支持
