### ISSUE TITLE
有人了解如何成立基金的吗，如果成立一个反996基金会有很大帮助的？

### ISSUE THREAD

**Issue by ianva** [Y1ran/Lambda-Stream-Dataprocess-Platform#18]
成立一个反996的基金会，可以用来支持所有因为996裁员的人和仍再996工作的人以法律的帮助，可以用基金成立相关的法律平台，让受到公司压迫的人得到合理的赔偿，并让996的公司付出代价。

**Comment by NeoZhangTCL** [comment]
成立一个NGO比较好吧，不过国内好像对NGO很反感

**Comment by ff4415** [comment]
有律师猎人就好了。 
律师集中接这样的维权案子，然后收取律师费用。
包括按比例分成都是可以接受的。 让非法律专业去自己维权太难了。 
有一个基金会来专门处理集中维权案例，请律师集体维权这样的问题就好了。

**Comment by DisMirror** [comment]
还是需要成立工会，由工会去专门搞这些事情
