### ISSUE TITLE
[杭州有赞科技有限公司-杭州-996-已裁员-无其他违法行为]

### ISSUE THREAD

**Issue by Y1ran** [Y1ran/Lambda-Stream-Dataprocess-Platform#2]
内容：....
仲裁条目: ...

愿意进行众筹聘请律师
愿意进行众筹购买微博热搜

其他补充条目

**Comment by zhaomeiru66** [comment]
Yeah it makes sense ,hope we can build a strong org to help more programmer to get their reasonable power.Thank you so much
