### ISSUE TITLE
腾讯长期剥削员工，公司内部使用各种盗版软件

### ISSUE THREAD

**Issue by ponyxu** [Y1ran/Lambda-Stream-Dataprocess-Platform#23]
腾讯长期剥削员工，公司内部使用各种盗版软件，比如photoshop/3d max/maya

**Comment by GodD6366** [comment]
腾讯这么大企业用盗版有点假吧

**Comment by xkai08** [comment]
生产的软件跟盗版差别有多大？

**Comment by funcman** [comment]
我个人购买的正版Photoshop CS6许可证被Adobe恶意回收了。
Adobe这么不尊重中国用户，其中一个很大原因就是因为连腾讯这样的大公司都在使用他们的盗版。

**Comment by stdxfs** [comment]
要揭就揭到底，取证录音图片。一个人一句话不能算数

**Comment by EstherLacan** [comment]
> 腾讯这么大企业用盗版有点假吧

人多而杂，想法越多内部的标准软件肯定满足不了需求的。我觉得盗版肯定有的。不过一般都是比较小众的软件。office，编辑器之类的一般都是正版。

**Comment by iamybj** [comment]
大家注意了啊，途家网这狗日的公司996不给加班费。还各种刁难逼员工主动走人。
[途家网不要脸，996加班不给加班费](https://iamybj.github.io/tujia/)

**Comment by ponyxu** [comment]
腾讯内部服务器上面全是盗版软件

**Comment by ponyxu** [comment]
还有破解版

**Comment by imfht** [comment]
@ponyxu photoshop 腾讯买了授权

**Comment by JerryGit1** [comment]
> 我个人购买的正版Photoshop CS6许可证被Adobe恶意回收了。
> Adobe这么不尊重中国用户，其中一个很大原因就是因为连腾讯这样的大公司都在使用他们的盗版。

那也感觉有点过份了啊，花钱了还回收

**Comment by pingcheng** [comment]
windows是正版的吗

**Comment by imfht** [comment]
@pingcheng Windows也是正版的。
公司买的机器都是带windows授权的

**Comment by m2nlight** [comment]
大家正版购买许可证尽量直接从官方购买，否则可能会已经为代理公司注销而导致许可证失效的。如果没有官方购买渠道，尽量用代替的软件。
