### ISSUE TITLE
建议996.icu主站加上程序员猝死案例

### ISSUE THREAD

**Issue by AlenSUN** [Y1ran/Lambda-Stream-Dataprocess-Platform#25]
1.既然是996.ICU，那不应该只提996，更要提ICU。
2.程序员猝死案例很多，过去相关报道一大堆，可以集中起来，并长期更新。
3.加上这个是为了给仍坚持在996一线的程序员提个醒，同时也可以给各位吃瓜群众对该行业目前的“病态”有进一步的了解。

**Comment by qinguoqing** [comment]
附议！

**Comment by liuqinglong110** [comment]
把华为猝死的案例贴上去，就足够了。

**Comment by 965ICU** [comment]
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

https://github.com/965ICU/996ICU/issues

**Comment by hsjwbbtyed** [comment]
十分赞同！

**Comment by DisMirror** [comment]
赞同

**Comment by 13116176539** [comment]
赞同
