### ISSUE TITLE
免费 劳动法及社保 专业咨询

### ISSUE THREAD

**Issue by H-baoxian** [Y1ran/Lambda-Stream-Dataprocess-Platform#26]
虽然只是作为HR/保险经纪人，但我很支持996.ICU的话题。

对于这个问题，可能很多人会说：
为什么要发起这个话题？这能够改变什么？
抱怨有什么用，一个公司待不下去，换一个公司不就好了？

我个人觉得：
这个话题，其实这不仅仅是抱怨！

是的，觉得一个公司待不下去了可以直接换，每个人总能找到工作。现在这个话题只是说，让大家都重视996，发出一些声音，企图改变些事情，而不是一直回避这问题。

这个话题的发起，就是不希望风气一直蔓延到整个行业，导致所有人无处可逃。

做不去了，换个工作，对于每一个人来说，应该是最容易做到的事情。但是！我们一直退避，最终，必然是退无可退。

程序猿一直不擅长发声，难得有人勇敢的发声。我们也一起帮帮忙，发出更响亮一些的声音。

996.ICU涉及的话题，也许不能完全改变IT行业996的问题，但是努力发出一些声音，总归能让行业气氛有一些变化，多努力努力，也许未来可期也不一定。

本人为资深HR，熟悉劳动法及社保相关政策，
如有朋友需要咨询，愿意贡献自己的一份力量~

**Comment by JasinYip** [comment]
@H-baoxian 非常赞！让我们共同努力，为所有劳动者争取合法权益！

我们不能看当自己公司变成 996 就只离开就算，我们必须要让这种风气遏制住，否则以后可能没有非 996 工作制公司可以选择了！
