### ISSUE TITLE
维权组织建设的建议

### ISSUE THREAD

**Issue by CQH628** [Y1ran/Lambda-Stream-Dataprocess-Platform#27]
#### 相关知识可以参考：

- 曼瑟尔 奥尔森（Mancur Olson）[《集体行动的逻辑》](https://www.lunwencloud.com/lunwen/economics/jingjililun/20170602/708791.html)

- 马斯·C. 谢林 （Thomas C Scheling）[《微观动机和宏观行为》](https://book.douban.com/subject/1446417/)
#### 组织建议：

- 每5-15人自由结成一个小组，内部随意自由讨论，对公共话题意见表达选出一个代言人。

- 每5个小组自由结成一个大组（包容25-75人），5位小组代言人对公共话题表达意见，选出1位代言人，1位监督人。大组只允许讨论大组公共话题。

- 每5个大组结成一个微信群，该群包括向下所有成员大约125-375人，大组代表和监督各5人为群管理员，群只允许讨论群级公共话题。每个群从大组代表和监督中选出1位代表和1位监督进入维权联盟，分别任理事和监事.

- 每5个群结成一个维权联盟，包含了5位理事和5位监督，负责联盟属下约625-1875人的代言。

- 每5个联盟可联合行动，大约包容了3125-9375人。

**说明：社会学和经济学知识已论证，5人集体是最佳议事和行动的单元。**

**Comment by hsjwbbtyed** [comment]
很棒的提议啊，大家尽快实施起来吧，然后不断在实践中改进各项规章和策略

**Comment by ff4415** [comment]
当务之急是先完善license。

**Comment by ff4415** [comment]
感谢推书。 先拜读一下。

**Comment by cqhwang** [comment]
#https://github.com/Y1ran/996.Law/issues/71#issuecomment-480475832
靠人多是否就能改变规则？
压力集团是一种组织。
