### ISSUE TITLE
关于这次运动的建议

### ISSUE THREAD

**Issue by hsjwbbtyed** [Y1ran/Lambda-Stream-Dataprocess-Platform#29]
1.咱们这个运动最初是为了程序员争取权益，等发展一段时间后也应当拉拢其他行业的无产阶级兄弟，比如环境，机械，材料，化学，生物等行业的从业人员，他们也是深受加班剥削的，我们要搞好统战工作，不断壮大力量。就像共产党初期只有工人阶级，后期也拉拢了农民阶级。谁是我们的敌人?谁是我们的朋友?这个问题是革命的首要问题，把我们的人搞得多多的，如此一来，这次新时代的工人运动才会有一个光明的前途。各位同志，我们一起为此努力吧！

2.或许我们应该在项目里加上共产党宣言和国际歌的file，以此唤醒更多人的阶级意识和斗争精神

**Comment by liues1992** [comment]
基于github很难发展其他行业的人，后期考虑扩展其他方式。

**Comment by hsjwbbtyed** [comment]
> 基于github很难发展其他行业的人，后期考虑扩展其他方式。

是啊，一步一步来吧。先在gayhub上把本行业的人发动了233，等时机到了再考虑其他方式

**Comment by wittyfans** [comment]
程序员因为有GitHub这么一个平台，容易联合在一起，其他行业的从业人员肯定没有那么幸运。事实上不管任何行业，都是雇主容易联合起来，想着怎么搜刮员工，因为雇主永远都在少数，而且容易联合，而劳动者却不一样。

眼下工会的作用有限，t程序员们通过许可证的方式约束公司确实是一个不错的方式，可以呼吁更多的大公司的项目加入，这就会增加对雇主的限制。

**Comment by 996-SZ** [comment]
强烈建议制定996.ICU社区的程序员守则，如果不能完全隔离一些不理智的谩骂，建议另外建一个沟通渠道，但是尽量跟 996.ICU 剥离。加强 996.ICU 的发言审核机制，法律只接受理智的言论和证据。
如果没有规范，也许这次运动的最后，只能沦为程序员相互的吐槽，和资本的笑料。

**Comment by marsprince** [comment]
确实，认清敌我很关键

**Comment by qianlishun** [comment]
应该团结起来所有无产阶级的同志们，996这不单单是IT行业的问题，是所有行业的问题。

**Comment by MillerRen** [comment]
> 1.咱们这个运动最初是为了程序员争取权益，等发展一段时间后也应当拉拢其他行业的无产阶级兄弟，比如环境，机械，材料，化学，生物等行业的从业人员，他们也是深受加班剥削的，我们要搞好统战工作，不断壮大力量。就像共产党初期只有工人阶级，后期也拉拢了农民阶级。谁是我们的敌人?谁是我们的朋友?这个问题是革命的首要问题，把我们的人搞得多多的，如此一来，这次新时代的工人运动才会有一个光明的前途。各位同志，我们一起为此努力吧！
> 
> 2.或许我们应该在项目里加上共产党宣言和国际歌的file，以此唤醒更多人的阶级意识和斗争精神

别到最后发展成一堆人的骂战,偏离了初衷.在github上不太合适:1.这是个代码托管平台 2.受众比较小

**Comment by hsjwbbtyed** [comment]
> > 1.咱们这个运动最初是为了程序员争取权益，等发展一段时间后也应当拉拢其他行业的无产阶级兄弟，比如环境，机械，材料，化学，生物等行业的从业人员，他们也是深受加班剥削的，我们要搞好统战工作，不断壮大力量。就像共产党初期只有工人阶级，后期也拉拢了农民阶级。谁是我们的敌人?谁是我们的朋友?这个问题是革命的首要问题，把我们的人搞得多多的，如此一来，这次新时代的工人运动才会有一个光明的前途。各位同志，我们一起为此努力吧！
> > 2.或许我们应该在项目里加上共产党宣言和国际歌的file，以此唤醒更多人的阶级意识和斗争精神
> 
> 别到最后发展成一堆人的骂战,偏离了初衷.在github上不太合适:1.这是个代码托管平台 2.受众比较小

是啊……很有道理，人一多就容易出现各种事，最后如果偏离初衷就太可惜了。的确这里受众有限，所以还是先在github上发动程序员吧

**Comment by obaiyan** [comment]
最怕猪队友和别有用心的人。刚刚还看到一个PR说要人肉开发360等浏览器的程序员。感觉就是故意送把柄给别人抓。
