### ISSUE TITLE
如何获取证据？

### ISSUE THREAD

**Issue by soganokouhei** [Y1ran/Lambda-Stream-Dataprocess-Platform#36]
比较容易获得的是打卡记录，但是一般这种东西属于电子版，很难作为证据。

另外，即便可以，开除当天你很可能连登录系统保存证据的机会都没，更遑论论证证据的真伪

**Comment by Melody1024** [comment]
在劳动关系中劳动者主要需要证明劳动关系存在、加班的事实存在、主张实际工资高于约定工资标准的应证明实际工资标准，主张被公司违法辞退的最好要有辞退通知…
司法优先认证据，空口无凭。电子证据要有原件或将电子证据进行公证。证据有三性：真实性、相关性、合法性。
要先弄清楚举证责任。然后弄清基本的民事法规及技巧。
具体可以关注https://github.com/Melody1024/workers.git项目

**Comment by soganokouhei** [comment]
比如，有个人拿着打卡记录去当证据，但是打卡记录是通过公司邮件发送的cls，公司会质问：你怎么证明这个xls不是你伪造的？

原本可以翻邮件来举证，但是实际操作中，邮箱很可能已经被公司冻结或删除了。

**Comment by Melody1024** [comment]
> 比如，有个人拿着打卡记录去当证据证明996或周工时大于72小时，但是打卡记录是通过公司邮件发送的xls，公司会在庭审中质问：你怎么证明这个xls不是你伪造的？
> 
> 原本可以翻邮件来举证，但是实际操作中，邮箱很可能已经被公司冻结或删除了。
> 
> @Melody1024 感觉您提到的项目里没有这种case

项目里现在的确没有专门的针对加班费的案例可以看下中兴和施颖的案例，这个有加班费。其实你说的问题是证据效力问题，公司的电子邮件如果你没有在公司取消权限前进行公证的话就基本没有效力，因为你只有截图没有原件。

**Comment by soganokouhei** [comment]
所以感觉是个死胡同

**Comment by Melody1024** [comment]
> 所以感觉是个死胡同 我总不能跟公司说借考勤机去公证吧。。。。

这个就看你想办法了，间接证据也可以，比如微信、qq聊天记录、公网邮件、公司承认加班的录音录像等。

**Comment by YJWWZHANG** [comment]
监控录像可以不，现在不是到处有摄像头的吗

**Comment by Melody1024** [comment]
> 监控录像可以不，现在不是到处有摄像头的吗

这个当然可以，但是别人会给你吗？

**Comment by flxtakuya** [comment]
电子记录格式源文件

**Comment by flxtakuya** [comment]
电子邮件的原始文件，outlook和foxmail可以直接复制出来
