### ISSUE TITLE
美团-北京-995-裁员不给N+1

### ISSUE THREAD

**Issue by GeemChen** [Y1ran/Lambda-Stream-Dataprocess-Platform#38]
坐标美团rd,2019年第三波裁员让自己走人，不给赔偿费，给了一两个月时间找工作，但是还被这段时间好好工作，求助求助

**Comment by Melody1024** [comment]
你的权益远不止n+1
具体可以关注https://github.com/Melody1024/workers.git项目

**Comment by Melody1024** [comment]
不要申请离职不要办理离职手续，也不要前任何其它协议和文件，如果给辞退通知拿着就行。违法解约的工资损失远超赔偿金。如果申请离职就一分钱没有，如果协商解约补偿也很少划不来。

**Comment by heyen-zxy** [comment]
这种情况最怕的是调岗吧，把你调去当骑手

**Comment by TsingJyujing** [comment]
> 这种情况最怕的是调岗吧，把你调去当骑手

补充一点哦，你Offer/劳动合同上是写着岗位的，除非只写着“员工”，否则应该是没法调你去当骑手的。
当时我们公司有两个做大数据的员工，上司要他们去开发后端，他们都依法拒绝了，因为合同上写的是Hadoop高级工程师。

**Comment by TsingJyujing** [comment]
注意千万不要自己签署任何自愿离职的材料，你要是被“自愿”了，没人能救得了你，先找工作，然后赖在公司，等他们拿着解雇你的材料来赶你走，找不到工作的话，不发N+1就赖着不走，有本事公司起诉你呀！不要怕！
如果解雇你以后，有的Offer该去就去，没发够N+1的，可以追诉的。
注意其中的1是待通知金，如果企业提前一个月通知你了，那赔偿金是N就行了，但是最后一个月的工资是要照发的。
祝你成功维护自己的合法权益。

**Comment by Melody1024** [comment]
> 注意千万不要自己签署任何自愿离职的材料，你要是被“自愿”了，没人能救得了你，先找工作，然后赖在公司，等他们拿着解雇你的材料来赶你走，找不到工作的话，不发N+1就赖着不走，有本事公司起诉你呀！不要怕！
> 如果解雇你以后，有的Offer该去就去，没发够N+1的，可以追诉的。
> 注意其中的1是待通知金，如果企业提前一个月通知你了，那赔偿金是N就行了，但是最后一个月的工资是要照发的。
> 祝你成功维护自己的合法权益。

1.如果是依法裁员就是N+1；这种情况少，通常都是以裁员未借口的；
2.违法解除劳动关系不是N+1，而是N+合同期(或违法解约期间)内的工资损失，具体可以看下https://github.com/Melody1024/workers_anti996_antiServility.git“经典参考案例_______最重要/工资损失_违法解约/经典案例/工资损失及经赔”里的经典裁判案例。

**Comment by GeemChen** [comment]
> 你的权益远不止n+1
> 具体可以关注https://github.com/Melody1024/workers.git 项目

多谢 已经加群了
