### ISSUE TITLE
合同里写明：员工应当在工资（包含奖金、加班费等）发放3日内提出异议

### ISSUE THREAD

**Issue by soganokouhei** [Y1ran/Lambda-Stream-Dataprocess-Platform#40]
合同里写明：员工应当在工资（包含奖金、加班费等）发放3日内提出异议，否则视同合理发放。

这样写的话一旦被裁是不是就不能针对过量加班提出赔偿了

**Comment by Melody1024** [comment]
是的，超期没有提出异议视为签字确认没有问题。大公司通常都这样约定，以减少签工资条的麻烦。具体也还存在变数，如果公司没有有效证据证明送达工资条给你就是变数。
