### ISSUE TITLE
对于口头传的995或996没有证据，只有打卡时间

### ISSUE THREAD

**Issue by yewuxue** [Y1ran/Lambda-Stream-Dataprocess-Platform#41]

**Comment by Melody1024** [comment]
《最高人民法院关于民事诉讼证据的若干规定》第二条 当事人对自己提出的诉讼请求所依据的事实或者反驳对方诉讼请求所依据的事实有 责任提供证据加以证明。  没有证据或者证据不足以证明当事人的事实主张的，由负有举证责任的当事人承担不利后 果。

**Comment by Melody1024** [comment]
《最高人民法院关于审理劳动争议案件适用法律若干问题的解释(三)》
第九条 劳动者主张加班费的，应当就加班事实的存在 承担举证责任。但劳动者有证据证明用人单位掌握加班 事实存在的证据，用人单位不提供的，由用人单位承担 不利后果。
