### ISSUE TITLE
如果考虑先默认996后收集证据,然后工作持续一段时间后索赔大额的想法是否可行？

### ISSUE THREAD

**Issue by GeniusLe** [Y1ran/Lambda-Stream-Dataprocess-Platform#43]
如果在司法上可以做到完全性的赔偿，那么直接去996上班，然后索赔，自然可以抑制这种垃圾风气

**Comment by Melody1024** [comment]
你的想法太幼稚了，你看到的加班费和违法解约赔偿金或经济补偿金都太少，不足以弥补实际损失。要懂基本的法律和司法知识才行，否则拿自己的时间做实验既不能保证成功也不一定成功。

**Comment by GeniusLe** [comment]
> 你的想法太幼稚了，你看到的加班费和违法解约赔偿金或经济补偿金都太少，不足以弥补实际损失。要懂基本的法律和司法知识才行，否则拿自己的时间做实验既不能保证成功也不一定成功。

我想你是否没有审题？其次你所定义幼稚那么你的成熟是什么？再其次，你能否提出一个一定能成功完全可以保护你的劳动权益的方法？还有请问你所说的不足以弥补实际损失是指什么？赔个公司给你？如果可以合法申诉并且获得在职期间所有付出时间的应有所得你还需要什么弥补？贪婪没有度数？

**Comment by Melody1024** [comment]
法律和司法问题我没有权力改变，但是最起码要知道自己有哪些权益存在并且敢于依法维权才有挽回自己权益损失的可能。具体可以看一下我的项目共享资料。
