### ISSUE TITLE
申请仲裁， 60个工作日，哪里等？你用什么等？收入还是时间，哎~~两行泪

### ISSUE THREAD

**Issue by AK47-dadada** [Y1ran/Lambda-Stream-Dataprocess-Platform#44]

**Comment by ff4415** [comment]
所以才需要建立自己的ngo组织，收集数据，聘请律师，跟进过程。

**Comment by AK47-dadada** [comment]
> 所以才需要建立自己的ngo组织，收集数据，聘请律师，跟进过程。

感觉不太靠谱吧，没有名人，大V，媒体报导，咱们只是飞蛾扑火而已，治标不治本。

**Comment by zimiyu** [comment]
60个工作日是最长时间，一般情况半个月就能有反馈，并且，起诉期间你是可以从事其他工作的。

**Comment by AK47-dadada** [comment]
> 60个工作日是最长时间，一般情况半个月就能有反馈，并且，起诉期间你是可以从事其他工作的。

你可能高看 zf这帮大爷的办事效率和准确性了。

**Comment by zimiyu** [comment]
> > 所以才需要建立自己的ngo组织，收集数据，聘请律师，跟进过程。
> 
> 感觉不太靠谱吧，没有名人，大V，媒体报导，咱们只是飞蛾扑火而已，治标不治本。

我就不信程序猿连流水线上的产业工人的能耐（没有歧视的意思），劳动法怎么来的？就是这群人用生命和自由换来的。

**Comment by zimiyu** [comment]
> > 60个工作日是最长时间，一般情况半个月就能有反馈，并且，起诉期间你是可以从事其他工作的。
> 
> 你可能高看 zf这帮大爷的办事效率和准确性了。

要有信心，由法律做支撑，有充足证据，再黑也黑不过去。我曾经是做农民工工伤维权援助的，见识过的黑暗场景很多，但是总体来说是还是明亮的多。

**Comment by AK47-dadada** [comment]
> > > 60个工作日是最长时间，一般情况半个月就能有反馈，并且，起诉期间你是可以从事其他工作的。
> > 
> > 
> > 你可能高看 zf这帮大爷的办事效率和准确性了。
> 
> 要有信心，由法律做支撑，有充足证据，再黑也黑不过去。我曾经是做农民工工伤维权援助的，见识过的黑暗场景很多，但是总体来说是还是明亮的多。

信心有，名人效应什么都可以改变，唯有不声不响的劳动阶级只有用时间、金钱、尊严去战斗，结果还是没有结果，我知道你心态好，但是我们不得不承认，没有影响力的我们，除了出卖自己的前途，别的会一无所获。加油我支持你们

**Comment by sndnvaps** [comment]
10个人以上，可以申请集体仲裁，这样速度会加快很多的。

**Comment by Melody1024** [comment]
要加班费和违法解约的胜诉概率低，不要过度期待。司法乱判现象多。可以花点时间看看https://github.com/Melody1024/workers_anti996_antiEnslavement.git里的资料，弄清下次自己该做什么。
