### ISSUE TITLE
其实大家都在走同一条失败的路：要加班费、拖欠的工资和违法解约赔偿金.....

### ISSUE THREAD

**Issue by Melody1024** [Y1ran/Lambda-Stream-Dataprocess-Platform#45]
被公司辞退还老老实实地申请离职，然后想报复一下公司打官司要加班费和赔偿金，结果基本败诉。即使赢了那点加班费和赔偿金或经济补偿金却远远不能弥补实际的违法违约损失。
对比一下《合同法》第113条，合同违约最大的损失是“合同履行后可以获得的利益”损失，对于劳务和劳动合同的可得利益损失即是全合同期内的工资损失，这个损失往往远超加班费和违法解约赔偿金。工资损失每损失一个月就是一个月的工资，而赔偿金是每6个月才赔偿一个月的工资，也就是说工资损失的赔偿率是违法解约赔偿金的6倍。
很可惜劳动合同法没有明确的对工资损失作定义，而只是在《违反《劳动法》有关劳动合同规定的赔偿办法》 第二、三条，《广东省工资支付条例》第二十九条，《辽宁省工资支付规定》第三十六条，《劳动法》第九十八条中有个模糊的定义，这就导致绝大多数人都不知道有工资损失的概念，也导致司法在适用的时候模糊空间太大。

**Comment by graphic-zhang** [comment]
不对，知乎live上资深HR里的live说，辞退打官司基本是劳动者赢

**Comment by Melody1024** [comment]
> 不对，知乎live上资深HR里的live说，辞退打官司基本是劳动者赢

你太乐观了。依据《最高人民法院关于民事诉讼证据的若干规定》第六条 在劳动争议纠纷案件中，因用人单位作出开除、除名、辞退、解除劳动合同、 减少劳动报酬、计算劳动者工作年限等决定而发生劳动争议的，由用人单位负举证责任。
确实解除劳动关系由用人单位举证，但是现实中存在几个非常严重的问题：
1、劳动者不懂证据意识，用人单位暗示或要求离职时，很多人都按照用人单位的要求申请离职或者协商离职，最后诉讼的时候铁定认定你是自愿离职的，因为作为完全民事行为能力人是你自己自愿申请离职的，你又主张单位辞退你又没有证据，空口无凭。这个情况确实没错，你自己申请离职的还说别人辞退你，谁都不会相信你；
2、用人单位不给书面辞退通知，口头辞退难以获得支持。依据《最高人民法院关于民事诉讼证据的若干规定》第六条解除劳动关系确实由用人单位承担全部举证责任，但是目前绝大多数省份的法院在这条的理解上有偏差，劳动者主张是用人单位辞退就要出具辞退通知等书面证据，否则你只是口头上说是辞退是不会被采信的，这就导致一个大漏洞：用人单位不给书面辞退通知你就绝对没有证据了；恰恰当你主张口头辞退公司又确认劳动关系已解除却又不承认是辞退反而主张你是自动离职的情况下，法院就会认为均不能证明离职原因就取一个中间值即协商解除，这样你最多只能拿到经济补偿金，而且你的劳动关系已经被认定解除了后面你再想反向主张，即既然不认可口头辞退那我就主张劳动关系没有解除索要工资的时候依据没机会了，因为前面的判决依据误判你们的劳动关系已解除；
目前只有江苏等少数几个地方认可口头辞退，其它地方一概不认，而且明显偏袒用人单位，比如你发一个空白的离职申请邮件都会认为你是自愿的，或者你先申请离职后又要到辞退通知大概率会被认为你是自愿的。
目前劳动争议不能直接申诉到最高法，导致各地各自为政，相同的事实每个地方的认定和判决结果都不一样。
可以查阅https://github.com/Melody1024/workers_anti996_antiServility.git里的“经典参考案例_______最重要/反例/”以及其它典型裁判案例了解。

**Comment by MillerRen** [comment]
> 被公司辞退还老老实实地申请离职，然后想报复一下公司打官司要加班费和赔偿金，结果基本败诉。即使赢了那点加班费和赔偿金或经济补偿金却远远不能弥补实际的违法违约损失。
> 对比一下《合同法》第113条，合同违约最大的损失是“合同履行后可以获得的利益”损失，对于劳务和劳动合同的可得利益损失即是全合同期内的工资损失，这个损失往往远超加班费和违法解约赔偿金。工资损失每损失一个月就是一个月的工资，而赔偿金是每6个月才赔偿一个月的工资，也就是说工资损失的赔偿率是违法解约赔偿金的6倍。
> 很可惜劳动合同法没有明确的对工资损失作定义，而只是在《违反《劳动法》有关劳动合同规定的赔偿办法》 第二、三条，《广东省工资支付条例》第二十九条，《辽宁省工资支付规定》第三十六条，《劳动法》第九十八条中有个模糊的定义，这就导致绝大多数人都不知道有工资损失的概念，也导致司法在适用的时候模糊空间太大。

法的执行和解释掌握在别人手里.就像地主定了一个法律可以告他儿子,结果就是谁告谁挨闷棍.部分农民翻身又成了地主,可能比之前的地主更加变本加厉.

**Comment by graphic-zhang** [comment]
你写了很多，感觉你也确实了解，只是感觉你的观点很是绝望，不符合人之常情和我了解的知识。
第一，绝大多数公司强行辞退人，都会愿意支付一定的赔偿，息事宁人，至于劳动者不懂法，被人力资源的巧言恶语劝住吓住了，那说明法理上还不是站在公司那边，他们只能用信息不对称吓人。
第二，劳动者和企业打官司会有公示，实际上对企业形象也有有损害的，如果是一个年轻的技术创业公司，那损害更大（融资，招人），所以企业只要不蠢的话，一般也不会和劳动者撕到这一步。
第三，我们国家有时候还是有点安闹分配的，从脸面上来说，工人是执政党的重要支柱，稳定是第一要素，所以立法的法理上是偏向工人的，但凡还有脸面上进心的企业应该会考虑社会政治背景的。
反正，我的意思是，不要被吓住了，忘了维护自己的权益，企业实际上也没有那么硬气。

**Comment by Melody1024** [comment]
> 你写了很多，感觉你也确实了解，只是感觉你的观点很是绝望，不符合人之常情和我了解的知识。
> 第一，绝大多数公司强行辞退人，都会愿意支付一定的赔偿，息事宁人，至于劳动者不懂法，被人力资源的巧言恶语劝住吓住了，那说明法理上还不是站在公司那边，他们只能用信息不对称吓人。
> 第二，劳动者和企业打官司会有公示，实际上对企业形象也有有损害的，如果是一个年轻的技术创业公司，那损害更大（融资，招人），所以企业只要不蠢的话，一般也不会和劳动者撕到这一步。
> 第三，我们国家有时候还是有点安闹分配的，从脸面上来说，工人是执政党的重要支柱，稳定是第一要素，所以立法的法理上是偏向工人的，但凡还有脸面上进心的企业应该会考虑社会政治背景的。
> 反正，我的意思是，不要被吓住了，忘了维护自己的权益，企业实际上也没有那么硬气。

并没有达到“绝望”的程度，如果对法治绝望这个国家早就动乱了，虽然你从一个公众的朴素正义观上分析有一定得道理，不过还是依据老话，你看到的永远只是冰山一角，不深入地了解是不会发现问题的。可以关注一下我的仓库的项目资料了解一下。

**Comment by MillerRen** [comment]
确实,劳动者和底层人民处于弱势,但仅仅发出声音还是不够的,声音很容易被埋没,因为媒体都是被控制的,需要其他各行各业的人士参与,尤其是法律界人士. 国企和央企攫取并垄断了高利润行业,创业也只能在一些低利润率的行业,这就导致了一些矛盾,干的多挣得少.如果不是寒冬,又有谁愿意断臂求生呢?996也是迫于无奈吧,总不能无缘无故的就把人辞退了.我这样理解,估计又有人喷了^_^.谁创业谁明白苦衷.
