### ISSUE TITLE
法律给劳动者的最后一根救命稻草-竞业限制经济补偿金

### ISSUE THREAD

**Issue by Melody1024** [Y1ran/Lambda-Stream-Dataprocess-Platform#46]
绝大部分劳动者第一次打官司要加班费和违法解约赔偿金的败诉率很高，很多人不知道的是法律也留给劳动者最后一根救命稻草，那就是离职后的竞业限制经济补偿金。
先翻一下劳动合同和保密(与竞业限制)协议里面有没有类似这样的一条：“离职后两年内不得自营或到与本公司生产或经营相同的产品或相同的业务的有竞争关系的企业任职”，如果有很可能就能拿到一笔不错的收入，注意是“很可能”不是绝对有，具体要看你的合同有没有约定前置生效条件。具体可以咨询或自行了解，切勿冲动行事。
竞业限制基本是给劳动者送钱，只要不违反竞业义务即可拿到经济补偿金。当今社会劳动关系不和谐，70%以上的公司合同里都有这个条款，那么不要把合同原件丢了，也不要认为离职了就和原公司没毛钱关系了。如果你手上已经有多份竞业协议恭喜你即将发个小财。等到期限(大多是2年)履行完毕后1年内再起诉，如果中途索要别人可以随时解除。
目前见过的最高的一份竞业限制经济补偿金是10个月支付了300W+元，(2017)苏0585民初3650号《3650迪皮埃复材构件(太仓)有限公司与纪军劳动争议一审民事判 决书》。

**Comment by sotex** [comment]
> 先翻一下劳动合同和保密(与竞业限制)协议里面有没有类似这样的一条：“离职后两年内不得自营或到与本公司生产或经营相同的产品或相同的业务”。

公司生产或经营的产品范围太广了，那岂不是很难再找公司，白等两年么？还是有相关的规定呢？

**Comment by Melody1024** [comment]
> > 先翻一下劳动合同和保密(与竞业限制)协议里面有没有类似这样的一条：“离职后两年内不得自营或到与本公司生产或经营相同的产品或相同的业务”。
> 
> 公司生产或经营的产品范围太广了，那岂不是很难再找公司，白等两年么？还是有相关的规定呢？

你提的问题很正常。
是否存在竞争性的比较应当以实际生产或经营的 产品和实际从事的业务的竞争性为基础，例如软件产品QQ音乐、百度音乐、网易云音乐都是从事数 字音乐版权交易服务的，存在竞争性;饿了么、美团外卖都从事网络订餐服务存在竞争性;支付宝、 云闪付都是第三方网络支付平台存在竞争性;其它等等。但是，虽然QQ音乐、饿了么、支付宝都是计 算机软件产品，但是其业务、目标用户完全不一样，不存在竞争性;再例如，空调、照相机、U盘、 电子门锁虽都是电子产品，但是其功能各不相同，也不存在竞争性。
建议你阅读https://github.com/Melody1024/workers.git 中“经典参考案例_______最重要/竞业限制”目录下的案例判决书来理解。
