### ISSUE TITLE
合同工资不实写怎么办？月薪12K，合同只有2000

### ISSUE THREAD

**Issue by long2ltoy** [Y1ran/Lambda-Stream-Dataprocess-Platform#48]
你们有这种情况吗？这种情况即使打官司也只能按合同来算，一天60块钱，一小时就8块钱，打下来一天加班费也就20几块钱！

一个月不到1000，你要是把一年的证据保存下来，也只能要到1万多，这还是要等几十天结果通知，并且仲裁胜诉的情况下。

**Comment by zimiyu** [comment]
有工资条的吧？去银行把工资流水拉出来作为证据，加班费、经济补偿金、追缴社保等是要按照实发工资计算的

**Comment by Melody1024** [comment]
工资条、银行支付流水、录取通知书、岗位说明、入职登记表、欠条…都可以

**Comment by long2ltoy** [comment]
感谢楼上两位
