### ISSUE TITLE
请不要把战火烧到github

### ISSUE THREAD

**Issue by MillerRen** [Y1ran/Lambda-Stream-Dataprocess-Platform#49]
请不要把战火烧到github,因为类似的具有极大争议性内容,github被封禁过,开发人员花了大量的时间和精力跟政府沟通,才让github继续开放,这是开发人员的最后一方净土,请善待它!

**Comment by Melody1024** [comment]
依法维权不存在任何法律问题。敢于维权发声才是正常的公民。满身奴性的人最终只会无路可走。

**Comment by MillerRen** [comment]
如果大家都只考虑自己和那些制定996规则的人没什么区别.

**Comment by yuminjustin** [comment]
> 请不要把战火烧到github,因为类似的具有极大争议性内容,github被封禁过,开发人员花了大量的时间和精力跟政府沟通,才让github继续开放,这是开发人员的最后一方净土,请善待它!

你想多了，国企基本没有996的，私企才有，不闹腾一下，私企制度只会越来越离谱

**Comment by srauni** [comment]
之前GITHUB被封是因为政治敏感，本质是和政府对抗。这次的事情完全符合中国法律规定，我们只是依照法律正常维护自己的权益，相关事件在国内也可以正常讨论，不存在战火的问题。

**Comment by srauni** [comment]
与其担心这件事会导致Github被封，不如考虑下如何防止这次的事件被有心人带偏导致Github被封

**Comment by Melody1024** [comment]
> > 请不要把战火烧到github,因为类似的具有极大争议性内容,github被封禁过,开发人员花了大量的时间和精力跟政府沟通,才让github继续开放,这是开发人员的最后一方净土,请善待它!
> 
> 你想多了，国企基本没有996的，私企才有，不闹腾一下，私企制度只会越来越离谱

民企之所以难生存这个问题的原因本质其实有如下几方面：
1、国内金融机构认为国企更有能力负债所以优先投资、贷款给国企，反之民企融资则更艰难；
2、早先民营企业家动不动就被冠以莫名其妙的罪行坐牢，比如物美张文忠案，坐了几十年牢直至2018年才宣告无罪；也有最近的西勘院千亿矿权案中的赵发琦；
这就导致民营企业家不得不处处碰壁、处处要谨慎，就是为什么当前国家一直在喊要保护民企合法权益的原因；
民营企业家难生存就导致其将这种情绪和压力发泄到员工身上，所以大家都难生存，处处碰壁处处要谨慎。
本来就是人情社会，民营企业家为了获得更多资源和项目，不得不低头和有资源有权的人搞好关系。这种风气自然而然地熏陶了民企，这就是为什么很多人不喜欢国企官僚作风去了民企以后发现更官僚更勾心斗角。

**Comment by salyuandua** [comment]
那些愿意用自由换取保障的人，既不配得到自由，又不配得到保障

**Comment by balthild** [comment]
> 与其担心这件事会导致Github被封，不如考虑下如何防止这次的事件被有心人带偏导致Github被封

最大的死穴可能是矛头所指包括华为等企业。它们虽然名义上是私企，但是有浓厚的国资成分。

**Comment by lpy96925** [comment]
希望我们可以少加班，默默祈祷！❤

**Comment by hui305** [comment]
有官方电报群吗？我们要组织起来！

**Comment by hui305** [comment]
狗奴才，你就是码奴！！！！
不支持也就算了，你可以不发声！

**Comment by graphic-zhang** [comment]
封就封呗，难道谷歌被封了你就不用了吗？那你可真是个弟弟

**Comment by MillerRen** [comment]
真的猛士,敢于正面刚,微博,Twitter都可以,可以直接去法院告.在这里逞什么能.

**Comment by MillerRen** [comment]
只有本身有奴性的人才动不动就讲奴才,别动不动就就地大小便,这不是撒野的地方.

**Comment by MillerRen** [comment]
如果一个人以持续的方式对待你,那一定是你允许的,否则他只能得逞一次.996还不都是被惯出来的,强烈支持反抗,反抗有多种形式,但是个人认为github不是合适的方式.

**Comment by Melody1024** [comment]
> 只有本身有奴性的人才动不动就讲奴才,别动不动就就地大小便,这不是撒野的地方.

看来你应该是在国企事业单位非民企工作的人了，满嘴透出文革思维、各种大道理。
正因为你这种人体会不到民众的痛苦，通过各种官僚手段压制奴役民众，导致民众维权意识差不敢维权，这种压制总有一天会反弹爆发，比如中美贸易战已经将体制架构上的问题暴露无遗。
作为年轻人，我们就是要直面当前问题，通过对自己权益维护的努力改善社会现状，国家才能民主进步，人民才能更加富裕。

**Comment by MillerRen** [comment]
1.我没有在国企工作过,但经历过,那才是真正的等级森严;公司也实行过995或加班,但是我不加班,如果因为这个要辞退我,那我可以告他.但仅仅是因为他说996我就天天加班,那也太听话了.
2.没有反对大家维权,只是不建议在github上搞维权,大家需要做的是请律师,把这些996的公司告破产,这才是直面问题.
3.996只是套路,很多公司用它裁员.真正有能力的人才不屑一顾.倒是有些人觊觎那些公司的高工资和福利,确又嚷嚷着说不人道.
4.如果你没法用手投票,还可以选择用脚投票,为啥要屈尊去一个996的公司呢?
5.我为每一个斗士点赞,但不包括那些谩骂别人的.自由不是你想做什么就做什么,而是你不想做什么就可以不做.

**Comment by MillerRen** [comment]
> 狗奴才，你就是码奴！！！！
> 不支持也就算了，你可以不发声！

... 智商堪忧,你啥时候看到我不支持了?

**Comment by MillerRen** [comment]
> 封就封呗，难道谷歌被封了你就不用了吗？那你可真是个弟弟

如果注册github就为了骂别人几句,那你又算什么东西?

**Comment by MillerRen** [comment]
> 那些愿意用自由换取保障的人，既不配得到自由，又不配得到保障

强烈支持,就怕有些人理解不了什么是真正的自由.

**Comment by MillerRen** [comment]
> 与其担心这件事会导致Github被封，不如考虑下如何防止这次的事件被有心人带偏导致Github被封

是的,我只是担心github被封,有可能很难再开放,参考sourceforge.

**Comment by yuminjustin** [comment]
> 2.没有反对大家维权,**只是不建议在github上搞维权**,大家需要做的是请律师,把这些996的公司告破产,这才是直面问题.

你别说了。。。。我的邮件越来越多，越描越黑。
1、绝大部分码农都注册了github；
2、github不受天朝管制；
所以说除了github还真没第二个地方能让这么多码农来抱怨。
。。。。。静观其变吧

**Comment by hsjwbbtyed** [comment]
> > 与其担心这件事会导致Github被封，不如考虑下如何防止这次的事件被有心人带偏导致Github被封
> 
> 是的,我只是担心github被封,有可能很难再开放,参考sourceforge.

封就封，翻墙不就行了，都是程序员了还不会翻墙？这点东西难不倒程序员的

**Comment by hsjwbbtyed** [comment]
> 1.我没有在国企工作过,但经历过,那才是真正的等级森严;公司也实行过995或加班,但是我不加班,如果因为这个要辞退我,那我可以告他.但仅仅是因为他说996我就天天加班,那也太听话了.
> 2.没有反对大家维权,只是不建议在github上搞维权,大家需要做的是请律师,把这些996的公司告破产,这才是直面问题.
> 3.996只是套路,很多公司用它裁员.真正有能力的人才不屑一顾.倒是有些人觊觎那些公司的高工资和福利,确又嚷嚷着说不人道.
> 4.如果你没法用手投票,还可以选择用脚投票,为啥要屈尊去一个996的公司呢?
> 5.我为每一个斗士点赞,但不包括那些谩骂别人的.自由不是你想做什么就做什么,而是你不想做什么就可以不做.

在github上不是搞维权，而是作为宣传阵地拉拢更多的人，唤醒他们的意识，这是一个统战阵地，就算要起诉这些公司也要劳动者集体诉讼，一个人的力量是单薄的，而通过平台宣传就是为了聚集力量。别总说什么“在github上抱怨有什么用”云云，任何运动都是先打舆论战，激起大家的反抗意识，有了理论的指导，最终才转化为轰轰烈烈的实践行为

**Comment by linxin6560** [comment]
> 真的猛士,敢于正面刚,微博,Twitter都可以,可以直接去法院告.在这里逞什么能.

微博。。。你真勇敢，封你都算小的。小心找你喝茶。

**Comment by NonvolatileMemory** [comment]
这不是一项政治运动，服从基于“中华人民共和国劳动法”，维护自身权益，何错之有？
依阁下之义，是否人民网亦应被当局墙掉？

**Comment by MillerRen** [comment]
> 这不是一项政治运动，服从基于“中华人民共和国劳动法”，维护自身权益，何错之有？
> 依阁下之义，是否人民网亦应被当局墙掉？

没有说这项运动有错,只是不要把免费的资源都玩死,大家都没得玩了.

**Comment by trotsky1997** [comment]
你装你🐴呢，爬开

**Comment by wangw469** [comment]
真的勇士，就算github被封，就会直接去法院告那封锁github的人。希望你可以是这样的勇士。

**Comment by NonvolatileMemory** [comment]
在github留言没有犯法，你不中意这种行为，可以选择自己放弃这种形式的发言，但是没有必要站在高地上一副冷嘲热讽并且自诩清高[e.g.: **在这里逞什么能**,**就怕有些人理解不了什么是真正的自由**, **别动不动就就地大小便**]的讽刺别人的发言。你和那些反对吃狗肉的人没有什么区别吧！

你有发表这种讽刺言论的自由，但是请不要忘记，我们也有批评你的自由。

另外关于墙的事情，若真的墙了github，错也不在于发声的人。中华人民共和国没有一项法律支持墙掉目前的GitHub。

> 如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是——但是：不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。 －－季业
送给您

**Comment by Melody1024** [comment]
> 在github留言没有犯法，你不中意这种行为，可以选择自己放弃这种形式的发言，但是没有必要站在高地上一副冷嘲热讽并且自诩清高[e.g.: **在这里逞什么能**,**就怕有些人理解不了什么是真正的自由**, **别动不动就就地大小便**]的讽刺别人的发言。你和那些反对吃狗肉的人没有什么区别吧！
> 
> 你有发表这种讽刺言论的自由，但是请不要忘记，我们也有批评你的自由。
> 
> 另外关于墙的事情，若真的墙了github，错也不在于发声的人。中华人民共和国没有一项法律支持墙掉目前的GitHub。
> 
> > 如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是——但是：不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。 －－季业
> > 送给您
我支持你的说法。不过网络安全法支持墙，再说别人要墙也不需要法律依据，一个“寻讯滋事”囊括了所有的罪名。不过我崇尚自由，who care...

**Comment by TimChen44** [comment]
这些项目在帮政府维护法律的尊严。

**Comment by qsc555** [comment]
你的立场也不是不能理解，一边害怕github被封不信任zf，另一边又渴望有一片净土；但就像你有自由接受现实窝着，也有人有提出抗议的自由和权利。你所谓的净土也只是你自己的想法，不能代表所有人。

**Comment by flxtakuya** [comment]
没有哪个公司敢攻击github

**Comment by MillerRen** [comment]
> 在github留言没有犯法，你不中意这种行为，可以选择自己放弃这种形式的发言，但是没有必要站在高地上一副冷嘲热讽并且自诩清高[e.g.: **在这里逞什么能**,**就怕有些人理解不了什么是真正的自由**, **别动不动就就地大小便**]的讽刺别人的发言。你和那些反对吃狗肉的人没有什么区别吧！
> 
> 你有发表这种讽刺言论的自由，但是请不要忘记，我们也有批评你的自由。
> 
> 另外关于墙的事情，若真的墙了github，错也不在于发声的人。中华人民共和国没有一项法律支持墙掉目前的GitHub。
> 
> > 如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是——但是：不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。 －－季业
> > 送给您

**若真的墙了github，错也不在于发声的人。** 确实是这样子的,没有人说在github上留言是错误的,但是github是一个代码托管平台,在这上面维权,还不如去白宫网站去请愿来的直接.我没有反对任何人维权,只是不建议在github上维权,那些只会出口骂人的人,你觉得他们是在维权吗?

**Comment by GitHub4Peter** [comment]
封就封呗，大不了隔离世界倒退五百年，瞎操什么战火心

**Comment by chenhaoxiang** [comment]
不知道阁下是满脸油腻的年迈大爷/大妈，还是如头像照片所示人模人样的年轻人。看了很久，发现你一直都在回，如果不是高级的五毛党，被洗脑者，那么就是一个傲娇自以为是的，沉浸在自我的世界无法自拔的小伙/姑娘了。能够反驳你的点太多了，就说说你的标题吧，最大的谬论就是把“战火烧到github”，996建立初衷就是为大家普及中国宪法以及中国劳动法，而不是要引起什么战争，合法的维护中国劳动者权益，符合中华人民共和国宪法以及中华人民共和国劳动法相关规定，并没有什么战火之说。如果你的标题是想把大家带偏，那么你这个智商堪忧。
另外你说的极大争议性又是从何而来的结论，凭借着网上的三言两语的评论吗？请问有何数据统计，如果有，请展示出来？资产阶级和工人阶级的极大争议！还是说劳动法和宪法模糊不清引起了极大争议！这块没有啥极大争议的（有争议的地方大家都心知肚明），中华人民共和国宪法和劳动法中有明确规定，如果不知，请移步996icu查看。  
再说自由，看了你的评论，自由不是想做什么就做什么，而是不想做什么便不做什么。简单的说一句吧。汝之自由非彼之自由，你自己所不愿的你可以选择不做，但是你不能强迫别人做别人所愿的或者不愿的。
你跳出来唱这个反调找骂吗？强迫别人不发声吗？不说你是工贼已经够好了。 
最后引用一首忏悔文送给你。
纳粹杀共产党时，
我没有出声
——因为我不是共产党员；
接着他们迫害犹太人，
我没有出声
——因为我不是犹太人；
然后他们杀工会成员，
我没有出声
——因为我不是工会成员；
后来他们迫害天主教徒，
我没有出声
——因为我是新教徒；
最后当他们开始对付我的时候，
已经没有人能站出来为我发声了。

而你，不仅仅是没有发声，还站到道德制高点指责发声之人，是何居心呢？ 

我基本没怎么发声，但也看不惯你这种站在道德制高点指责发声之人的人，因为我谨记：
“如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是——但是：不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。”

**Comment by riverchu** [comment]
不知道这位真正的猛士做了什么正面刚的事情呢？还是单纯怕大家抗议导致他自己的利益受损，才让大家不要靠近他自己心目中的净土。要是这样的话，不过就是个高高挂起的懦夫，没什么资格说别人。

**Comment by xaut531457199** [comment]
我就看不惯你这种人，老是在唱反调

**Comment by MillerRen** [comment]
> 不知道阁下是满脸油腻的年迈大爷/大妈，还是如头像照片所示人模人样的年轻人。看了很久，发现你一直都在回，如果不是高级的五毛党，被洗脑者，那么就是一个傲娇自以为是的，沉浸在自我的世界无法自拔的小伙/姑娘了。能够反驳你的点太多了，就说说你的标题吧，最大的谬论就是把“战火烧到github”，996建立初衷就是为大家普及中国宪法以及中国劳动法，而不是要引起什么战争，合法的维护中国劳动者权益，符合中华人民共和国宪法以及中华人民共和国劳动法相关规定，并没有什么战火之说。如果你的标题是想把大家带偏，那么你这个智商堪忧。
> 另外你说的极大争议性又是从何而来的结论，凭借着网上的三言两语的评论吗？请问有何数据统计，如果有，请展示出来？资产阶级和工人阶级的极大争议！还是说劳动法和宪法模糊不清引起了极大争议！这块没有啥极大争议的（有争议的地方大家都心知肚明），中华人民共和国宪法和劳动法中有明确规定，如果不知，请移步996icu查看。
> 再说自由，看了你的评论，自由不是想做什么就做什么，而是不想做什么便不做什么。简单的说一句吧。汝之自由非彼之自由，你自己所不愿的你可以选择不做，但是你不能强迫别人做别人所愿的或者不愿的。
> 你跳出来发表“你们这群傻子，别到我这个高贵的地盘发表言论”，你是找骂吗？强迫别人不发声吗？不说你是工贼已经够好了。
> 最后引用一首忏悔文送给你。
> 纳粹杀共产党时，
> 我没有出声
> ——因为我不是共产党员；
> 接着他们迫害犹太人，
> 我没有出声
> ——因为我不是犹太人；
> 然后他们杀工会成员，
> 我没有出声
> ——因为我不是工会成员；
> 后来他们迫害天主教徒，
> 我没有出声
> ——因为我是新教徒；
> 最后当他们开始对付我的时候，
> 已经没有人能站出来为我发声了。
> 
> 而你，不仅仅是没有发声，还站到道德制高点指责发声之人，是何居心呢？
> 
> 我基本没怎么发声，但也看不惯你这种站在道德制高点指责发声之人的人，因为我谨记：
> “如果天总也不亮，那就摸黑过生活；如果发出声音是危险的，那就保持沉默；如果自觉无力发光，那就别去照亮别人。但是——但是：不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意洋洋；不要嘲讽那些比自己更勇敢、更有热量的人们。可以卑微如尘土，不可扭曲如蛆虫。”

我发出这样的观点,就是找骂,看看这些人的底线. 如果他们只是一群网络暴民,乌合之众,我觉得他们维权必定失败,只有找出来为什么996的根本原因才能从根本上解决问题.如果他们只是讨薪,争取赔偿,那就没有必要把自己包装的那么伟大.我最担心的事情就是他们把github的评论当做发泄的地方,所过之处寸草不生,所以他们做他们的事情,我做我的事情,我看了那些评论的人,在github贡献基本没有,请他们远离这个代码托管平台.

**Comment by MillerRen** [comment]
> 不知道这位真正的猛士做了什么正面刚的事情呢？还是单纯怕大家抗议导致他自己的利益受损，才让大家不要靠近他自己心目中的净土。要是这样的话，不过就是个高高挂起的懦夫，没什么资格说别人。

我就是个懦夫,所以我要维护这个伟大的代码托管平台,不被践踏.

**Comment by MillerRen** [comment]
> 我就看不惯你这种人，老是在唱反调

不唱反调,你怎么能知道这些人是不是盟友,能不能加入呢

**Comment by MillerRen** [comment]
有人准备了一份不996的公司名单,大家可以去试试这些公司.
https://github.com/formulahendry/955.WLB
