### ISSUE TITLE
360,腾讯这些不要脸的玩意把996.icu的网址全部封掉了

### ISSUE THREAD

**Issue by wuzhjian** [Y1ran/Lambda-Stream-Dataprocess-Platform#52]

**Comment by yuminjustin** [comment]
你没图没真相，我发个图吧，哈哈哈
![image](https://user-images.githubusercontent.com/8414340/55371286-3bb4b300-5530-11e9-88e1-a71cdc6f4dbe.png)

**Comment by yuminjustin** [comment]
再来个微信的

![image](https://user-images.githubusercontent.com/8414340/55371665-94d11680-5531-11e9-8581-80923caa0f3d.png)

不过，话说回来，应该不是360和腾讯做的事情，他们本就是舆论的中心之一了，绝对不会主动趟这趟浑水，自毁长城的，应该是其他人搞的。

**Comment by newbe36524** [comment]
Chrome 与 360极速浏览器 的区别
![image](https://user-images.githubusercontent.com/7685462/55402593-66315b00-5586-11e9-8038-81f806584b55.png)

**Comment by firedom** [comment]
这些企业认为如果不接受强制加班可以辞职，因为这些企业认为只有少数人会愿意走人。但是当有一个组织要求这些企业认真执行劳动法的时候这些企业反而开始害怕了。

这或许说明了人力资源对这些企业来说依然是不可替代的，之前用辞职吓唬员工只是一种让你不敢离职的手段而已。

**Comment by NonvolatileMemory** [comment]
微信安卓端好像没问题呀

**Comment by NonvolatileMemory** [comment]
难道是因为我在香港的原因？
刚试过，微信安卓端是可以访问的。

**Comment by JerryGit1** [comment]
> 难道是因为我在香港的原因？
> 刚试过，微信安卓端是可以访问的。

微信安卓好像都可以访问

**Comment by wanyanjiabin** [comment]
再一次用行动向我们证明,这些浏览器的安全性及其堪忧,后台可以操控你指定的网址跳转或报毒.用于打击和诬陷,诱导和欺骗使用用户.比如qq如果和淘宝交恶,可以指定qq浏览器访问淘宝时跳转至诈骗网站,让用户觉得是淘宝诈骗.(仅极端推演).作为程序员,请使用chrome,放弃国内的浏览器或放弃一些恶意拦截用户操作,恶意引导用户的浏览器.

**Comment by MisterOwen** [comment]
楼上说可以访问的指的不是GitHub上的页面吧，指的应该是996.ICU。亲测后者的确没有被封，前者才是被各家浏览器封杀的对象

**Comment by yttrium3** [comment]
> 再一次用行动向我们证明,这些浏览器的安全性及其堪忧,后台可以操控你指定的网址跳转或报毒.用于打击和诬陷,诱导和欺骗使用用户.比如qq如果和淘宝交恶,可以指定qq浏览器访问淘宝时跳转至诈骗网站,让用户觉得是淘宝诈骗.(仅极端推演).作为程序员,请使用chrome,放弃国内的浏览器或放弃一些恶意拦截用户操作,恶意引导用户的浏览器.

作为程序员，请使用Chromium或者Firefox，放弃Chrome，因为谷歌也不是什么好鸟，Chrome也不过是搜刮数据的工具之一，比如Chrome带的software reporter tool就会在后台扫描电脑上安装的程序（更蠢的是这东西一点都不低调，直接把CPU跑满了，这才让我从任务管理器里揪了出来），但Chromium里是没有的。
https://chromium.woolyss.com/

**Comment by torchina** [comment]
聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by torchina** [comment]
> > Once again, we can prove to us that the security of these browsers is worrying. The background can control the URLs you specify or jump to the poison. It is used to combat and frame, induce and deceive users. For example, if qq and Taobao are evil, You can specify the qq browser to visit Taobao when you visit Taobao, so that users think it is Taobao fraud. (Extremely only). As a programmer, please use chrome, give up the domestic browser or give up some malicious interception of user operations, malicious guidance User's browser.
> 
> As a programmer, please use Chromium or Firefox, give up Chrome, because Google is not a good bird, Chrome is just one of the tools to search data, such as Chrome's software reporter tool will scan the program installed on the computer in the background ( Even more stupid is that this thing is not low-key, directly running the CPU, which makes me out of the task manager), but there is no Chromium. 
> [Https://chromium.woolyss.com/](https://chromium.woolyss.com/)

聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get
