### ISSUE TITLE
目前维权可能会导致失业，这才是最大的问题

### ISSUE THREAD

**Issue by jaune162** [Y1ran/Lambda-Stream-Dataprocess-Platform#53]
维权可能会导致失业。
通过维权向法院诉讼，最终肯定能够胜诉。但是维权成本太高，最终即便是胜诉了公司赔偿了。但是有很大的可能会被公司辞退。而且其他公司如果知道你有这样的背景，找工作可能也会受到影响。

还是大家法律意识淡薄，只有少数人站起来发声是不够的，很快就会被淹没。应该组织更多行业的从业人员，不能只局限于IT行业。

**Comment by SkyAndGround** [comment]
中国还是穷人太多。。。

**Comment by Melody1024** [comment]
> 维权可能会导致失业。
> 通过维权向法院诉讼，最终肯定能够胜诉。但是维权成本太高，最终即便是胜诉了公司赔偿了。但是有很大的可能会被公司辞退。而且其他公司如果知道你有这样的背景，找工作可能也会受到影响。
> 
> 还是大家法律意识淡薄，只有少数人站起来发声是不够的，很快就会被淹没。应该组织更多行业的从业人员，不能只局限于IT行业。

正因为大家都是你这种心态：不敢依法维权，所以社会劳动关系才如此不和谐。

**Comment by MillerRen** [comment]
> 维权可能会导致失业。
> 通过维权向法院诉讼，最终肯定能够胜诉。但是维权成本太高，最终即便是胜诉了公司赔偿了。但是有很大的可能会被公司辞退。而且其他公司如果知道你有这样的背景，找工作可能也会受到影响。
> 
> 还是大家法律意识淡薄，只有少数人站起来发声是不够的，很快就会被淹没。应该组织更多行业的从业人员，不能只局限于IT行业。

很多运动,发展到最后,往往成了一个发泄的地方,已经偏离了最初的方向.

**Comment by Melody1024** [comment]
楼上的兄弟，首先声明我不是在追打你。
但是，看起来你现在感觉很安全，现实会让你恐慌，不信我可以给一些磨灭人性的判决书你看，任何一个有良知的人都能看出问题。
2017-2018多起因劳动争议发生的暴力事件就是最好的证明。网上都有报道。

**Comment by jaune162** [comment]
> > 维权可能会导致失业。
> > 通过维权向法院诉讼，最终肯定能够胜诉。但是维权成本太高，最终即便是胜诉了公司赔偿了。但是有很大的可能会被公司辞退。而且其他公司如果知道你有这样的背景，找工作可能也会受到影响。
> > 还是大家法律意识淡薄，只有少数人站起来发声是不够的，很快就会被淹没。应该组织更多行业的从业人员，不能只局限于IT行业。
> 
> 正因为大家都是你这种心态：不敢依法维权，所以社会劳动关系才如此不和谐。
> 如果别人是违法辞退你会赔偿很多，可以看https://github.com/Melody1024/workers_anti996_antiServility.git 里的资料。

所以还是法律意识淡薄，不懂得通过法律的手段维护自己的利益

**Comment by MillerRen** [comment]
> 楼上的兄弟，首先声明我不是在追打你。
> 但是，看起来你现在感觉很安全，现实会让你恐慌，不信我可以给一些磨灭人性的判决书你看，任何一个有良知的人都能看出问题。
> 2017-2018多起因劳动争议发生的暴力事件就是最好的证明。网上都有报道。

正常讨论,没什么的.我也是没有安全感,才一直提升自己的实力,只有这样才有选择的余地.我经历过比这黑暗的事实(在派出所被关20多小时被打,但是我最后坚持住了,没有被派出所吞掉不属于他们的钱),996这类事情绝不是个例,讨论这些很容易上升到政治层面.

**Comment by Melody1024** [comment]
> > 楼上的兄弟，首先声明我不是在追打你。
> > 但是，看起来你现在感觉很安全，现实会让你恐慌，不信我可以给一些磨灭人性的判决书你看，任何一个有良知的人都能看出问题。
> > 2017-2018多起因劳动争议发生的暴力事件就是最好的证明。网上都有报道。
> 
> 正常讨论,没什么的.我也是没有安全感,才一直提升自己的实力,只有这样才有选择的余地.我经历过比这黑暗的事实(在派出所被关20多小时被打,但是我最后坚持住了,没有被派出所吞掉不属于他们的钱),996这类事情绝不是个例,讨论这些很容易上升到政治层面.

可以在提起行政诉讼并索要国家赔偿，作为类不需要原告提交证据，。
劳动案件不喷井式爆发难以提升司法裁判质量维护公平正义。主要问题是劳动者维权意识太弱，奴性太深。

**Comment by jaune162** [comment]
大家理性讨论，不要太偏激

**Comment by firedom** [comment]
是否可以尝试通过制作游戏的方式让因为不满996而失业的人仍可在失业期间获取一定的收入？

----
如果建立一个组织做一个游戏比如996模拟器是否可以让更多人知道这件事和996带来的危害？
If we want to publicize 996 question further, can we build a project to make a 996-like game? 
for instance **996 Working Simulator**.
https://github.com/lxlxw/996.TSC/issues/31

**Comment by firedom** [comment]
我的意思是，我们并不是一定要为喜欢压榨员工的公司工作才有钱赚，通过其他方式作出贡献也一样可以获得收入。

**Comment by Melody1024** [comment]
> 我的意思是，我们并不是一定要为喜欢压榨员工的公司工作才有钱赚，通过其他方式作出贡献也一样可以获得收入。

996和失业问题是法律和司法问题，只有宣传法律知识唤醒广大劳动者的维权意识才能解决问题，劳动者不主动争取任何人都帮不了忙。

**Comment by tldzyx** [comment]
先唱个国歌, 再翻翻历史课本.

**Comment by gtx1080** [comment]
> 是否可以尝试通过制作游戏的方式让因为不满996而失业的人仍可在失业期间获取一定的收入？
> 
> 如果建立一个组织做一个游戏比如996模拟器是否可以让更多人知道这件事和996带来的危害？
> If we want to publicize 996 question further, can we build a project to make a 996-like game?
> for instance **996 Working Simulator**.
> [lxlxw/996.TSC#31](https://github.com/lxlxw/996.TSC/issues/31)

听起来不错，这样能让更多非IT界的工作者认识到996并且参与进来
（然后游戏就被屏蔽了，跟这个repository一样）

**Comment by firedom** [comment]
> > 是否可以尝试通过制作游戏的方式让因为不满996而失业的人仍可在失业期间获取一定的收入？
> > 如果建立一个组织做一个游戏比如996模拟器是否可以让更多人知道这件事和996带来的危害？
> > If we want to publicize 996 question further, can we build a project to make a 996-like game?
> > for instance **996 Working Simulator**.
> > [lxlxw/996.TSC#31](https://github.com/lxlxw/996.TSC/issues/31)
> 
> 听起来不错，这样能让更多非IT界的工作者认识到996并且参与进来
> （然后游戏就被屏蔽了，跟这个repository一样）

即使真的屏蔽了，想玩的人依然可以通过科学上网玩到。

**Comment by flxtakuya** [comment]
曝光的材料越多越好，量变引起质变。
