### ISSUE TITLE
受到996.ICU启发，建立了一个No Social Security do(no)t Work 

### ISSUE THREAD

**Issue by imfannet** [Y1ran/Lambda-Stream-Dataprocess-Platform#57]
其实，作为非996工作的一员，十分支持996.ICU项目进行，也很赞同不知道是哪里看来的一句话”这事儿成了，十年以后再来看，肯定是一件好事。“  
受到996.ICU项目启发，这段时间周边有几位非开发者也正在寻找工作，看到了也想到了一个对于劳动者比较严重但更为底层的问题：”没有社保“  
很多较为底层的工作（尤其是小公司提供的工作），如果不为劳动者提供社会保险，我想病了以后，除非倾家荡产，可能连ICU都没资格进吧。  
No Social Security do(no)t Work

**Comment by Melody1024** [comment]
请查看我的项目资料，传播正能量，传播法律知识，唤醒劳动者的维权意识。

**Comment by lucaisacoder** [comment]
支持，我想我们今天在这里讨论的不是个别人的学历、长相受到了歧视，当然这些也应该包含在工作权益之内。更广泛的讲，这应该是一场启蒙运动，唤醒大家的权益意识，让整个行业更加健康的发展。目前极有可能达不到任何实质改善，但作为一种理念会植根于大家的心中。

**Comment by Melody1024** [comment]
其实要感谢美国打贸易战让所有的问题都暴露出来，不然依然是温水煮青蛙大家还在忍耐
