### ISSUE TITLE
劳动者法律互助Q群(进入看号码)广告勿扰

### ISSUE THREAD

**Issue by Melody1024** [Y1ran/Lambda-Stream-Dataprocess-Platform#59]
劳动者法律互助群：先加中转群146224708然后我邀请到群368223405（可能已满）480807977（因为讨论的内容包括合法的黑技术已经不能直接搜索了^_^ ）。
不收费、劳动者互助分享社群，律师、广告份子勿入！

**Comment by TheoJiang** [comment]
qq群吗？被封了？搜不到。

**Comment by Melody1024** [comment]
> qq群吗？被封了？搜不到。

我居然现在才知道搜不到，我去。换成这个群聊号码：146224708
