### ISSUE TITLE
易车网-北京-996-裁员不给N+1封顶10w

### ISSUE THREAD

**Issue by resistance996** [Y1ran/Lambda-Stream-Dataprocess-Platform#60]
易车网顶峰作案，4月开始实行996，并且不报销餐费，报销打车费也从加班到9点改成了10点。
裁员没有N+1，谣传最多10万赔偿。
易车网CEO张序安去年年薪7亿人民币，位居亚洲第二。

**Comment by Melody1024** [comment]
1.不要申请离职、不要办任何离职手续，不要签任何协议和文件，不要承认任何对自己不利的事情；一旦签了铁定就败诉；如果给书面辞退通知就拿着(记得要有公章)；
2. 加班证据提前收集好，比如加班相关的邮件(自动)转发到外网私人邮箱等；
