### ISSUE TITLE
魅族自带浏览器已挂

### ISSUE THREAD

**Issue by yan-gong** [Y1ran/Lambda-Stream-Dataprocess-Platform#61]
![7c8bf05a63cbdb8ac4fe7d8b5e27579](https://user-images.githubusercontent.com/43055436/55454933-3c267a00-5614-11e9-89dd-7c2587273933.jpg)

**Comment by lijinghuatongxue** [comment]
魅族垃圾

**Comment by ksnzh** [comment]
> 魅族垃圾

魅族是有阿里投资吧
