### ISSUE TITLE
展示你们的证据，但不应该被删除，区块链能够更好的记录真实的证据

### ISSUE THREAD

**Issue by bossssssout** [Y1ran/Lambda-Stream-Dataprocess-Platform#63]
看到很多ITer发出所谓的证据后，出于某些原因，导致相关页面404

区块链能够更好收集及展示证据。

但是我只是一个运营汪，你们还是需要自己动手操作一下的=。=

拜了个拜

**Comment by Zxilly** [comment]
github已经是门槛了，区块链成本更高
而且感觉在国内的网络环境下区块链挺麻烦的

**Comment by bossssssout** [comment]
对于动手能力Max的ITer来说...这点门槛应该还行吧

但是肯定会有一部分人进不来的

**Comment by pingcheng** [comment]
这么小的链。。。大公司联合起来+国家层面出手，分分钟改你的链

**Comment by n55555852** [comment]
> 这么小的链。。。大公司联合起来+国家层面出手，分分钟改你的链

可以考虑，直接写在以太坊的传送上，不过不能发照片，只能发文字。
