### ISSUE TITLE
大小周是不是也应该可以考虑进来，是否也是违法行为，如果加班是否有补偿

### ISSUE THREAD

**Issue by laziobird** [Y1ran/Lambda-Stream-Dataprocess-Platform#65]
大小周：

资料：

大小周是现今国内公司一种奇怪的休息方式。是指一个星期上六天班（只休息星期天一天），下一个星期只上五天班（休星期六和星期天两天），再个星期又只休一天，再下一个星期又休两天，如此循环。

**Comment by Tedko** [comment]
https://github.com/kattgu7/Anti-996-License

参考license中遵守劳动法的那条。已经包括。
