### ISSUE TITLE
996ICU被各大互联网公司屏蔽了

### ISSUE THREAD

**Issue by chenfei2341** [Y1ran/Lambda-Stream-Dataprocess-Platform#67]
360急速浏览器屏蔽996ICU，使用360急速浏览器访问github中这个项目会说不安全，然后自动跳转404，这个是我自己试过的，根据凤凰科技的消息，其余百度，搜狗，QQ等浏览器也屏蔽了996ICU项目。
访问会提示不安全。
[#996icu遭大公司联手屏蔽#](https://weibo.com/1856404484/HnTrwh3pd?from=page_1002061856404484_profile&wvr=6&mod=weibotime&type=comment#_rnd1554347158236)
我在微博上转发后除非自己登陆，否则看不到，真是秀...

**Comment by ponyxu** [comment]
太不要脸了

**Comment by flxtakuya** [comment]
无所谓了，木已成舟。

**Comment by torchina** [comment]
聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by snakeliwei** [comment]
> 聊天室 - 没有自我审查
> https://gitter.im/torchina/community
> 
> Tor 浏览器 8.0.8 - 绕过gfw
> https://torchina.github.io/get

浏览器屏蔽，chrome是正常访问的
