### ISSUE TITLE
996ICU为啥关闭了 Issues?

### ISSUE THREAD

**Issue by Force-King** [Y1ran/Lambda-Stream-Dataprocess-Platform#7]

**Comment by worldbeatiful** [comment]
不晓得啊

**Comment by worldbeatiful** [comment]
这个有点过分了

**Comment by wangzhijiang00** [comment]
真的是非常讨厌加班， 现在快30了， 身体明显下滑的厉害， 从毕业到现在基本上没过过正常人的日子， 太煎熬了， 还不如回家种地，哎， 如果能改变是多好啊。

**Comment by zb2947244682** [comment]
为了分类，把问题分类

**Comment by worldbeatiful** [comment]
什么时候能好
看不见评论我很急

**Comment by 965ICU** [comment]
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

https://github.com/965ICU/996ICU/issues

**Comment by ShuaiShuaiLee** [comment]
里面有人大量发广告，还有谈政治。言论不可控!
容易出事，关了比较安全!

**Comment by ShuaiShuaiLee** [comment]
我上面的那个965ICU的就是发广告的傻逼!
链接是个外包公司的广告，哪都有他!傻逼!

**Comment by ShuaiShuaiLee** [comment]
里面有人大量发广告，还有谈政治。言论不可控!
容易出事，关了比较安全!
