### ISSUE TITLE
关于《劳动保障监察条例》分析和利用条例的具体行动（暨志愿者召集公告）

### ISSUE THREAD

**Issue by CPdogson** [Y1ran/Lambda-Stream-Dataprocess-Platform#74]
关于《劳动保障监察条例》分析和利用条例的具体行动（暨志愿者召集公告）

一、法律可行性分析
1.1 《劳动保障监察条例》条文简析
《劳动保障监察条例》是2004年施行，规定公权力机关如何主动保护劳动者权益的法律。
第九条：任何组织或者个人对违反劳动保障法律、法规或者规章的行为，有权向劳动保障行政部门举报。劳动者认为用人单位侵犯其劳动保障合法权益的，有权向劳动保障行政部门投诉。
第十一条：劳动保障行政部门对下列事项实施劳动保障监察：（五）用人单位遵守工作时间和休息休假规定的情况；
第十四条：劳动保障监察以日常巡视检查、审查用人单位按照要求报送的书面材料以及接受举报投诉等形式进行。
第二十五条：用人单位违反劳动保障法律、法规或者规章延长劳动者工作时间的，由劳动保障行政部门给予警告，责令限期改正，并可以按照受侵害的劳动者每人100元以上500元以下的标准计算，处以罚款。
但从法律条文来看，根据第十四条和第二十五条地方的劳动局是有巡视本地企业违反劳动法情况的义务，并且有处罚权；根据第九条，第三人有举报地方企业违法的权利。最后，劳动局根据处罚情况是有财政收入的，我想他们应该很乐意去干。
1.2 《关于实施<劳动保障监察条例>若干规定》
《关于实施<劳动保障监察条例>若干规定》经劳动和社会保障讨论通过，现予公布，自2005施行。
第六条 劳动保障行政部门对用人单位及其劳动场所的日常巡视检查，应当制定年度计划和 中长期规划，确定重点检查范围，并按照现场检查的规定进行。
第九条 劳动保障行政部门应当设立举报、投诉信箱，公开举报、投诉电话，依法查处举报和投诉反映的违反劳动保障法律的行为。
第四十六条 地方各级劳动保障行政部门应当按照劳动保障部有关规定对承办的案件进行统计并填表上报。
该规定是我们信息公开的主要依据，一说明各级劳动局有一份年度计划，第二点说明各级劳动局上级有对案件的统计。另外，也印证了《劳动保障监察条例》中的第三方举报可行性。
注：目前“劳动保障部门”已并入“人力资源和社会保障部”，劳动监察大队是隶属于人力资源和社会保障局的事业单位，故上下文中的“劳动部“均指“人力资源和社会保障部“，”劳动局“指地方的”人力资源和社会保障局“。
二、行动方案
2.1 信息公开——《劳动保障监察条例》运行状况
2.1.1 目的
对于信息公开获取的信息，可以帮助分析问题，比如为何劳动法执行不严，是劳动监察大队人手不足、权限不够？还是其中有贪污存在？信息公开的除了获取信息外，还可以给予当地部门压力，毕竟公开一份丑陋的报告是非常难看的，信息公开是一个可诉行为，如果认为信息公开结果不真实等任何不满，可以制造大量的行政复议和行政诉讼。
2.1.2 信息公开对象
市级人力资源和社会保障局，如北京市人力资源和社会保障局、广州市人力资源和社会保障局。选择市一级的部门，真是因为他不大不小刚刚好的政治地位，比起国、省级，市级有着更多的直接资料，并且面临着省、国级的压力。
2.1.3 信息公开内容
信息公开申请表可以在政府网站下载，信息公开内容仁者见仁智者见智，一般情况下我们认为越模糊越好，但也要有针对性。本人在此抛砖引玉，写一个范例。对象以广州市人力资源和社会保障局为例。
根据《关于实施<劳动保障监察条例>若干规定》第六条、第九条、第四十六条以及《中华人民共和国政府信息公开条例》规定，现要求公开：
1、2018年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
2、2019年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
3、广州市设立的举报、投诉信箱地址，公开举报、投诉电话号码
4、广州市2017年度关于按照劳动保障部有关规定对承办的案件统计表
5、广州市2018年度关于按照劳动保障部有关规定对承办的案件统计表
2.1.4 信息公开邮寄地址等事宜
信息公开邮递建议：使用EMS邮寄，勾选妥投通知，在备注栏中写到信息公开申请。
信息公开地址获取（广州例）：打开广州市人力资源和社会保障局，找到信息公开（政府公开）一栏，打开“信息公开指南“，找到”依申请公开“部分获取下载《广州市人力资源和社会保障局政府信息公开申请表》，在政府信息公开工作机构部分获取邮寄地址。
2.1.5 信息公开后续活动
信息公开后，将会有两条线路
2.1.5.1 行政复议、行政诉讼路线，《信息公开条例》一般要求15个工作日内公开，如果信息公开的结果敷衍，甚至不公开，那么可以进行行政诉讼和行政复议。
2.1.5.2 传阅报告，指出公开报告不足，并找媒体加以宣传。
2.2、线上第三方举报机构建立
该行动目的是为了解决维权可能会导致失业问题的，也是大家所关心的一个问题，个人实名举报可能导致企业报复。
该机构将会以一个民间线上组织的名义向劳动局举报，如以996icu的名义（当然我不知道以该名义是否合适，我也并未获得授权）。
该机构也希望成立志愿律师团团队，为实名举报者提供法律帮助。

三、志愿者召集
本行动实施需要一些愿意实名加入我们的志愿者，承担信息公开，举报的行动。
以及一些匿名的行动者加入，进行搜集举报所需的证据。
由衷的希望各位star的朋友，可以踊跃参加到行动中来。
联系邮箱：CPdogson@protonmail.com

四、声明
本行动所有行为均将以事实为依据，以法律为准绳。本行动行为目的为促进劳动法施行，保护劳动者权益。

附：《关于应对996工作制的本质法律原因和应对策略》
[https://github.com/Y1ran/996.Law/issues/70](url)
《信息公开指导手册》
[https://github.com/mdrights/mirror-CN/blob/master/%E6%89%8B%E5%86%8C%E5%92%8C%E6%8C%87%E5%8D%97/%E6%94%BF%E5%BA%9C%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E7%94%B3%E8%AF%B7%E6%89%8B%E5%86%8C.pdf
](url)

**Comment by CPdogson** [comment]
可能由于操作失误，所附链接需要使用复制的方式才能打开

**Comment by Melody1024** [comment]
> 关于《劳动保障监察条例》分析和利用条例的具体行动（暨志愿者召集公告）
> 
> 一、法律可行性分析
> 1.1 《劳动保障监察条例》条文简析
> 《劳动保障监察条例》是2004年施行，规定公权力机关如何主动保护劳动者权益的法律。
> 第九条：任何组织或者个人对违反劳动保障法律、法规或者规章的行为，有权向劳动保障行政部门举报。劳动者认为用人单位侵犯其劳动保障合法权益的，有权向劳动保障行政部门投诉。
> 第十一条：劳动保障行政部门对下列事项实施劳动保障监察：（五）用人单位遵守工作时间和休息休假规定的情况；
> 第十四条：劳动保障监察以日常巡视检查、审查用人单位按照要求报送的书面材料以及接受举报投诉等形式进行。
> 第二十五条：用人单位违反劳动保障法律、法规或者规章延长劳动者工作时间的，由劳动保障行政部门给予警告，责令限期改正，并可以按照受侵害的劳动者每人100元以上500元以下的标准计算，处以罚款。
> 但从法律条文来看，根据第十四条和第二十五条地方的劳动局是有巡视本地企业违反劳动法情况的义务，并且有处罚权；根据第九条，第三人有举报地方企业违法的权利。最后，劳动局根据处罚情况是有财政收入的，我想他们应该很乐意去干。
> 1.2 《关于实施<劳动保障监察条例>若干规定》
> 《关于实施<劳动保障监察条例>若干规定》经劳动和社会保障讨论通过，现予公布，自2005施行。
> 第六条 劳动保障行政部门对用人单位及其劳动场所的日常巡视检查，应当制定年度计划和 中长期规划，确定重点检查范围，并按照现场检查的规定进行。
> 第九条 劳动保障行政部门应当设立举报、投诉信箱，公开举报、投诉电话，依法查处举报和投诉反映的违反劳动保障法律的行为。
> 第四十六条 地方各级劳动保障行政部门应当按照劳动保障部有关规定对承办的案件进行统计并填表上报。
> 该规定是我们信息公开的主要依据，一说明各级劳动局有一份年度计划，第二点说明各级劳动局上级有对案件的统计。另外，也印证了《劳动保障监察条例》中的第三方举报可行性。
> 注：目前“劳动保障部门”已并入“人力资源和社会保障部”，劳动监察大队是隶属于人力资源和社会保障局的事业单位，故上下文中的“劳动部“均指“人力资源和社会保障部“，”劳动局“指地方的”人力资源和社会保障局“。
> 二、行动方案
> 2.1 信息公开——《劳动保障监察条例》运行状况
> 2.1.1 目的
> 对于信息公开获取的信息，可以帮助分析问题，比如为何劳动法执行不严，是劳动监察大队人手不足、权限不够？还是其中有贪污存在？信息公开的除了获取信息外，还可以给予当地部门压力，毕竟公开一份丑陋的报告是非常难看的，信息公开是一个可诉行为，如果认为信息公开结果不真实等任何不满，可以制造大量的行政复议和行政诉讼。
> 2.1.2 信息公开对象
> 市级人力资源和社会保障局，如北京市人力资源和社会保障局、广州市人力资源和社会保障局。选择市一级的部门，真是因为他不大不小刚刚好的政治地位，比起国、省级，市级有着更多的直接资料，并且面临着省、国级的压力。
> 2.1.3 信息公开内容
> 信息公开申请表可以在政府网站下载，信息公开内容仁者见仁智者见智，一般情况下我们认为越模糊越好，但也要有针对性。本人在此抛砖引玉，写一个范例。对象以广州市人力资源和社会保障局为例。
> 根据《关于实施<劳动保障监察条例>若干规定》第六条、第九条、第四十六条以及《中华人民共和国政府信息公开条例》规定，现要求公开：
> 1、2018年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> 2、2019年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> 3、广州市设立的举报、投诉信箱地址，公开举报、投诉电话号码
> 4、广州市2017年度关于按照劳动保障部有关规定对承办的案件统计表
> 5、广州市2018年度关于按照劳动保障部有关规定对承办的案件统计表
> 2.1.4 信息公开邮寄地址等事宜
> 信息公开邮递建议：使用EMS邮寄，勾选妥投通知，在备注栏中写到信息公开申请。
> 信息公开地址获取（广州例）：打开广州市人力资源和社会保障局，找到信息公开（政府公开）一栏，打开“信息公开指南“，找到”依申请公开“部分获取下载《广州市人力资源和社会保障局政府信息公开申请表》，在政府信息公开工作机构部分获取邮寄地址。
> 2.1.5 信息公开后续活动
> 信息公开后，将会有两条线路
> 2.1.5.1 行政复议、行政诉讼路线，《信息公开条例》一般要求15个工作日内公开，如果信息公开的结果敷衍，甚至不公开，那么可以进行行政诉讼和行政复议。
> 2.1.5.2 传阅报告，指出公开报告不足，并找媒体加以宣传。
> 2.2、线上第三方举报机构建立
> 该行动目的是为了解决维权可能会导致失业问题的，也是大家所关心的一个问题，个人实名举报可能导致企业报复。
> 该机构将会以一个民间线上组织的名义向劳动局举报，如以996icu的名义（当然我不知道以该名义是否合适，我也并未获得授权）。
> 该机构也希望成立志愿律师团团队，为实名举报者提供法律帮助。
> 
> 三、志愿者召集
> 本行动实施需要一些愿意实名加入我们的志愿者，承担信息公开，举报的行动。
> 以及一些匿名的行动者加入，进行搜集举报所需的证据。
> 由衷的希望各位star的朋友，可以踊跃参加到行动中来。
> 联系邮箱：[CPdogson@protonmail.com](mailto:CPdogson@protonmail.com)
> 
> 四、声明
> 本行动所有行为均将以事实为依据，以法律为准绳。本行动行为目的为促进劳动法施行，保护劳动者权益。
> 
> 附：《关于应对996工作制的本质法律原因和应对策略》
> [https://github.com/Y1ran/996.Law/issues/70](url)
> 《信息公开指导手册》
> [https://github.com/mdrights/mirror-CN/blob/master/%E6%89%8B%E5%86%8C%E5%92%8C%E6%8C%87%E5%8D%97/%E6%94%BF%E5%BA%9C%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E7%94%B3%E8%AF%B7%E6%89%8B%E5%86%8C.pdf ](url)

别浪费时间了，劳动监察根本不理你，只是偶尔帮人数众多的务工人员象征性地讨讨薪，根本不理你上班族。某些地区劳动监察根本不对外不直接接待劳动者，而是要先去劳动调解信访，这些人也不懂法律，用人单位不同意时就直接叫你去仲裁，你没有任何办法；信访不是必须受理的事项，《行政诉讼法》规定信访不可以起诉，所以最后劳动信访和劳动监察就是摆设不了了之......最多给你起个诉讼时效中断的作用；目前只有诉讼才有可能帮你。不信你可以去劳动行政部门试试。
把时间浪费在这个上不如多看看资料：https://github.com/Melody1024/workers_anti996_antiServility.git

**Comment by CPdogson** [comment]
> > 关于《劳动保障监察条例》分析和利用条例的具体行动（暨志愿者召集公告）
> > 一、法律可行性分析
> > 1.1 《劳动保障监察条例》条文简析
> > 《劳动保障监察条例》是2004年施行，规定公权力机关如何主动保护劳动者权益的法律。
> > 第九条：任何组织或者个人对违反劳动保障法律、法规或者规章的行为，有权向劳动保障行政部门举报。劳动者认为用人单位侵犯其劳动保障合法权益的，有权向劳动保障行政部门投诉。
> > 第十一条：劳动保障行政部门对下列事项实施劳动保障监察：（五）用人单位遵守工作时间和休息休假规定的情况；
> > 第十四条：劳动保障监察以日常巡视检查、审查用人单位按照要求报送的书面材料以及接受举报投诉等形式进行。
> > 第二十五条：用人单位违反劳动保障法律、法规或者规章延长劳动者工作时间的，由劳动保障行政部门给予警告，责令限期改正，并可以按照受侵害的劳动者每人100元以上500元以下的标准计算，处以罚款。
> > 但从法律条文来看，根据第十四条和第二十五条地方的劳动局是有巡视本地企业违反劳动法情况的义务，并且有处罚权；根据第九条，第三人有举报地方企业违法的权利。最后，劳动局根据处罚情况是有财政收入的，我想他们应该很乐意去干。
> > 1.2 《关于实施<劳动保障监察条例>若干规定》
> > 《关于实施<劳动保障监察条例>若干规定》经劳动和社会保障讨论通过，现予公布，自2005施行。
> > 第六条 劳动保障行政部门对用人单位及其劳动场所的日常巡视检查，应当制定年度计划和 中长期规划，确定重点检查范围，并按照现场检查的规定进行。
> > 第九条 劳动保障行政部门应当设立举报、投诉信箱，公开举报、投诉电话，依法查处举报和投诉反映的违反劳动保障法律的行为。
> > 第四十六条 地方各级劳动保障行政部门应当按照劳动保障部有关规定对承办的案件进行统计并填表上报。
> > 该规定是我们信息公开的主要依据，一说明各级劳动局有一份年度计划，第二点说明各级劳动局上级有对案件的统计。另外，也印证了《劳动保障监察条例》中的第三方举报可行性。
> > 注：目前“劳动保障部门”已并入“人力资源和社会保障部”，劳动监察大队是隶属于人力资源和社会保障局的事业单位，故上下文中的“劳动部“均指“人力资源和社会保障部“，”劳动局“指地方的”人力资源和社会保障局“。
> > 二、行动方案
> > 2.1 信息公开——《劳动保障监察条例》运行状况
> > 2.1.1 目的
> > 对于信息公开获取的信息，可以帮助分析问题，比如为何劳动法执行不严，是劳动监察大队人手不足、权限不够？还是其中有贪污存在？信息公开的除了获取信息外，还可以给予当地部门压力，毕竟公开一份丑陋的报告是非常难看的，信息公开是一个可诉行为，如果认为信息公开结果不真实等任何不满，可以制造大量的行政复议和行政诉讼。
> > 2.1.2 信息公开对象
> > 市级人力资源和社会保障局，如北京市人力资源和社会保障局、广州市人力资源和社会保障局。选择市一级的部门，真是因为他不大不小刚刚好的政治地位，比起国、省级，市级有着更多的直接资料，并且面临着省、国级的压力。
> > 2.1.3 信息公开内容
> > 信息公开申请表可以在政府网站下载，信息公开内容仁者见仁智者见智，一般情况下我们认为越模糊越好，但也要有针对性。本人在此抛砖引玉，写一个范例。对象以广州市人力资源和社会保障局为例。
> > 根据《关于实施<劳动保障监察条例>若干规定》第六条、第九条、第四十六条以及《中华人民共和国政府信息公开条例》规定，现要求公开：
> > 1、2018年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> > 2、2019年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> > 3、广州市设立的举报、投诉信箱地址，公开举报、投诉电话号码
> > 4、广州市2017年度关于按照劳动保障部有关规定对承办的案件统计表
> > 5、广州市2018年度关于按照劳动保障部有关规定对承办的案件统计表
> > 2.1.4 信息公开邮寄地址等事宜
> > 信息公开邮递建议：使用EMS邮寄，勾选妥投通知，在备注栏中写到信息公开申请。
> > 信息公开地址获取（广州例）：打开广州市人力资源和社会保障局，找到信息公开（政府公开）一栏，打开“信息公开指南“，找到”依申请公开“部分获取下载《广州市人力资源和社会保障局政府信息公开申请表》，在政府信息公开工作机构部分获取邮寄地址。
> > 2.1.5 信息公开后续活动
> > 信息公开后，将会有两条线路
> > 2.1.5.1 行政复议、行政诉讼路线，《信息公开条例》一般要求15个工作日内公开，如果信息公开的结果敷衍，甚至不公开，那么可以进行行政诉讼和行政复议。
> > 2.1.5.2 传阅报告，指出公开报告不足，并找媒体加以宣传。
> > 2.2、线上第三方举报机构建立
> > 该行动目的是为了解决维权可能会导致失业问题的，也是大家所关心的一个问题，个人实名举报可能导致企业报复。
> > 该机构将会以一个民间线上组织的名义向劳动局举报，如以996icu的名义（当然我不知道以该名义是否合适，我也并未获得授权）。
> > 该机构也希望成立志愿律师团团队，为实名举报者提供法律帮助。
> > 三、志愿者召集
> > 本行动实施需要一些愿意实名加入我们的志愿者，承担信息公开，举报的行动。
> > 以及一些匿名的行动者加入，进行搜集举报所需的证据。
> > 由衷的希望各位star的朋友，可以踊跃参加到行动中来。
> > 联系邮箱：[CPdogson@protonmail.com](mailto:CPdogson@protonmail.com)
> > 四、声明
> > 本行动所有行为均将以事实为依据，以法律为准绳。本行动行为目的为促进劳动法施行，保护劳动者权益。
> > 附：《关于应对996工作制的本质法律原因和应对策略》
> > [https://github.com/Y1ran/996.Law/issues/70](url)
> > 《信息公开指导手册》
> > [https://github.com/mdrights/mirror-CN/blob/master/%E6%89%8B%E5%86%8C%E5%92%8C%E6%8C%87%E5%8D%97/%E6%94%BF%E5%BA%9C%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E7%94%B3%E8%AF%B7%E6%89%8B%E5%86%8C.pdf ](url)
> 
> 别浪费时间了，劳动监察根本不理你，只是偶尔帮人数众多的“务工人员”象征性地讨讨薪，根本不理你上班族。某些地区劳动监察根本不对外不直接接待劳动者，而是要先去劳动调解信访，这些人也不懂法律，用人单位不同意时就直接叫你去仲裁，你没有任何办法；信访不是必须受理的事项，《行政诉讼法》规定信访不可以起诉，所以最后劳动信访和劳动监察就是摆设不了了之......最多给你起个诉讼时效中断的作用；目前只有诉讼才【有可能】帮你。不信你可以去劳动行政部门试试。诉讼程序会直接累死你的，你不会有时间和精力去纠结这些边缘事情。
> 把时间浪费在这个上不如多看看资料：https://github.com/Melody1024/workers_anti996_antiServility.git

我认同你的大部分观点，仲裁和诉讼是最有效的途径我也清楚。但是与公司发生仲裁和诉讼，当事人的在公司待下去也是被冷处理。对于个人而言，诉讼和仲裁相当于王炸，炸完之后拿到补偿，工作也丢了。
我的做法并非让“劳动监察部门”理我，而是公共增加压力，引发公众参与和媒体舆论，是从传播和公众参与的角度考虑的，而你的角度是保护当事人个人的角度考虑的。
另外，“信访”不可诉，但《信息公开条例》第三十三条规定，信息公开是可复议可诉性质的，如果不了解请不要妄加言论。如何把一个不可诉行为转化为可诉，也是法律工作者的工作之一。

**Comment by CPdogson** [comment]
已转移至 https://github.com/CPdogson/996action

**Comment by Melody1024** [comment]
> > > 关于《劳动保障监察条例》分析和利用条例的具体行动（暨志愿者召集公告）
> > > 一、法律可行性分析
> > > 1.1 《劳动保障监察条例》条文简析
> > > 《劳动保障监察条例》是2004年施行，规定公权力机关如何主动保护劳动者权益的法律。
> > > 第九条：任何组织或者个人对违反劳动保障法律、法规或者规章的行为，有权向劳动保障行政部门举报。劳动者认为用人单位侵犯其劳动保障合法权益的，有权向劳动保障行政部门投诉。
> > > 第十一条：劳动保障行政部门对下列事项实施劳动保障监察：（五）用人单位遵守工作时间和休息休假规定的情况；
> > > 第十四条：劳动保障监察以日常巡视检查、审查用人单位按照要求报送的书面材料以及接受举报投诉等形式进行。
> > > 第二十五条：用人单位违反劳动保障法律、法规或者规章延长劳动者工作时间的，由劳动保障行政部门给予警告，责令限期改正，并可以按照受侵害的劳动者每人100元以上500元以下的标准计算，处以罚款。
> > > 但从法律条文来看，根据第十四条和第二十五条地方的劳动局是有巡视本地企业违反劳动法情况的义务，并且有处罚权；根据第九条，第三人有举报地方企业违法的权利。最后，劳动局根据处罚情况是有财政收入的，我想他们应该很乐意去干。
> > > 1.2 《关于实施<劳动保障监察条例>若干规定》
> > > 《关于实施<劳动保障监察条例>若干规定》经劳动和社会保障讨论通过，现予公布，自2005施行。
> > > 第六条 劳动保障行政部门对用人单位及其劳动场所的日常巡视检查，应当制定年度计划和 中长期规划，确定重点检查范围，并按照现场检查的规定进行。
> > > 第九条 劳动保障行政部门应当设立举报、投诉信箱，公开举报、投诉电话，依法查处举报和投诉反映的违反劳动保障法律的行为。
> > > 第四十六条 地方各级劳动保障行政部门应当按照劳动保障部有关规定对承办的案件进行统计并填表上报。
> > > 该规定是我们信息公开的主要依据，一说明各级劳动局有一份年度计划，第二点说明各级劳动局上级有对案件的统计。另外，也印证了《劳动保障监察条例》中的第三方举报可行性。
> > > 注：目前“劳动保障部门”已并入“人力资源和社会保障部”，劳动监察大队是隶属于人力资源和社会保障局的事业单位，故上下文中的“劳动部“均指“人力资源和社会保障部“，”劳动局“指地方的”人力资源和社会保障局“。
> > > 二、行动方案
> > > 2.1 信息公开——《劳动保障监察条例》运行状况
> > > 2.1.1 目的
> > > 对于信息公开获取的信息，可以帮助分析问题，比如为何劳动法执行不严，是劳动监察大队人手不足、权限不够？还是其中有贪污存在？信息公开的除了获取信息外，还可以给予当地部门压力，毕竟公开一份丑陋的报告是非常难看的，信息公开是一个可诉行为，如果认为信息公开结果不真实等任何不满，可以制造大量的行政复议和行政诉讼。
> > > 2.1.2 信息公开对象
> > > 市级人力资源和社会保障局，如北京市人力资源和社会保障局、广州市人力资源和社会保障局。选择市一级的部门，真是因为他不大不小刚刚好的政治地位，比起国、省级，市级有着更多的直接资料，并且面临着省、国级的压力。
> > > 2.1.3 信息公开内容
> > > 信息公开申请表可以在政府网站下载，信息公开内容仁者见仁智者见智，一般情况下我们认为越模糊越好，但也要有针对性。本人在此抛砖引玉，写一个范例。对象以广州市人力资源和社会保障局为例。
> > > 根据《关于实施<劳动保障监察条例>若干规定》第六条、第九条、第四十六条以及《中华人民共和国政府信息公开条例》规定，现要求公开：
> > > 1、2018年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> > > 2、2019年广州市劳动保障行政部门对用人单位及其劳动场所日常巡视检查的年度计划
> > > 3、广州市设立的举报、投诉信箱地址，公开举报、投诉电话号码
> > > 4、广州市2017年度关于按照劳动保障部有关规定对承办的案件统计表
> > > 5、广州市2018年度关于按照劳动保障部有关规定对承办的案件统计表
> > > 2.1.4 信息公开邮寄地址等事宜
> > > 信息公开邮递建议：使用EMS邮寄，勾选妥投通知，在备注栏中写到信息公开申请。
> > > 信息公开地址获取（广州例）：打开广州市人力资源和社会保障局，找到信息公开（政府公开）一栏，打开“信息公开指南“，找到”依申请公开“部分获取下载《广州市人力资源和社会保障局政府信息公开申请表》，在政府信息公开工作机构部分获取邮寄地址。
> > > 2.1.5 信息公开后续活动
> > > 信息公开后，将会有两条线路
> > > 2.1.5.1 行政复议、行政诉讼路线，《信息公开条例》一般要求15个工作日内公开，如果信息公开的结果敷衍，甚至不公开，那么可以进行行政诉讼和行政复议。
> > > 2.1.5.2 传阅报告，指出公开报告不足，并找媒体加以宣传。
> > > 2.2、线上第三方举报机构建立
> > > 该行动目的是为了解决维权可能会导致失业问题的，也是大家所关心的一个问题，个人实名举报可能导致企业报复。
> > > 该机构将会以一个民间线上组织的名义向劳动局举报，如以996icu的名义（当然我不知道以该名义是否合适，我也并未获得授权）。
> > > 该机构也希望成立志愿律师团团队，为实名举报者提供法律帮助。
> > > 三、志愿者召集
> > > 本行动实施需要一些愿意实名加入我们的志愿者，承担信息公开，举报的行动。
> > > 以及一些匿名的行动者加入，进行搜集举报所需的证据。
> > > 由衷的希望各位star的朋友，可以踊跃参加到行动中来。
> > > 联系邮箱：[CPdogson@protonmail.com](mailto:CPdogson@protonmail.com)
> > > 四、声明
> > > 本行动所有行为均将以事实为依据，以法律为准绳。本行动行为目的为促进劳动法施行，保护劳动者权益。
> > > 附：《关于应对996工作制的本质法律原因和应对策略》
> > > [https://github.com/Y1ran/996.Law/issues/70](url)
> > > 《信息公开指导手册》
> > > [https://github.com/mdrights/mirror-CN/blob/master/%E6%89%8B%E5%86%8C%E5%92%8C%E6%8C%87%E5%8D%97/%E6%94%BF%E5%BA%9C%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E7%94%B3%E8%AF%B7%E6%89%8B%E5%86%8C.pdf ](url)
> > 
> > 
> > 别浪费时间了，劳动监察根本不理你，只是偶尔帮人数众多的“务工人员”象征性地讨讨薪，根本不理你上班族。某些地区劳动监察根本不对外不直接接待劳动者，而是要先去劳动调解信访，这些人也不懂法律，用人单位不同意时就直接叫你去仲裁，你没有任何办法；信访不是必须受理的事项，《行政诉讼法》规定信访不可以起诉，所以最后劳动信访和劳动监察就是摆设不了了之......最多给你起个诉讼时效中断的作用；目前只有诉讼才【有可能】帮你。不信你可以去劳动行政部门试试。诉讼程序会直接累死你的，你不会有时间和精力去纠结这些边缘事情。
> > 把时间浪费在这个上不如多看看资料：https://github.com/Melody1024/workers_anti996_antiServility.git
> 
> 我认同你的大部分观点，仲裁和诉讼是最有效的途径我也清楚。但是与公司发生仲裁和诉讼，当事人的在公司待下去也是被冷处理。对于个人而言，诉讼和仲裁相当于王炸，炸完之后拿到补偿，工作也丢了。
> 我的做法并非让“劳动监察部门”理我，而是公共增加压力，引发公众参与和媒体舆论，是从传播和公众参与的角度考虑的，而你的角度是保护当事人个人的角度考虑的。
> 另外，“信访”不可诉，但《信息公开条例》第三十三条规定，信息公开是可复议可诉性质的，如果不了解请不要妄加言论。如何把一个不可诉行为转化为可诉，也是法律工作者的工作之一。

如果你懂法你可以去试试，看看信访是如何对待你的。等你好消息。你要是能把不可诉的转化为可诉的，我膜拜。
