### ISSUE TITLE
OPPO自带浏览器也不行了

### ISSUE THREAD

**Issue by flxtakuya** [Y1ran/Lambda-Stream-Dataprocess-Platform#75]

**Comment by torchina** [comment]
聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by Cekerel** [comment]
vivo自带浏览器的祖传版本还能直接访问,但是最新版本的自带浏览器就不行了。

**Comment by ManjuGanio** [comment]
华为的可以，火狐也可以。
