### ISSUE TITLE
呼吁在公开信得不到建设性回应后组织示威

### ISSUE THREAD

**Issue by naimen** [Y1ran/Lambda-Stream-Dataprocess-Platform#85]
看到.petition那边已经开始向相关部门和总工会请愿了。不过以现在形式来看，我们虽然在舆论略占上风，不过却没有什么实际作用，几大公司均无表态。现在向政府部门请愿估计也得不到积极的回应，毕竟相对于保证这些企业的存活和效益，我们一群打工仔能不能多活几年根本无足轻重。

所以我认为，如果在劳动节前还没有建设性的进展，我们应该利用长假向企业抗议和示威，特别针对华为，京东，阿里和腾讯这种领头羊公司，这么做有三点好处：
1. 没有比劳动节更好的日子哦
2. 博得更大的公众关注
3. 以实际行动来施压，逼迫资方表态，摆脱僵局

以上，欢迎拍砖

**Comment by lyxllq** [comment]
主要矛头应该针对加班不给加班费的企业。
华为应该是良心公司，虽然是狼性公司，但是肉多。华为公司很多利润都能发放到员工手中。听说主动辞职也能有补偿金发放。我认为这样的公司还是不错的。

绝大多数公司学到了华为的狼性，但是不给肉吃。
